### ISSUE TITLE
编译pdf文档时出现问题

### ISSUE THREAD

**Issue by zhong-yy** [gmt-china/GMT_docs#1069]
## 问题描述

**编译过程**
```
下载
git clone --depth=1 https://github.com/gmt-china/china-geospatial-data.git
git clone --depth=10 https://github.com/gmt-china/GMT_docs.git

export GMT_DATADIR=/home/zhongyiyuan/china-geospatial-data

编译
make latexpdf
```

**错误**
```
[104]
第6章

LaTeX Warning: File `{_images/d44026c69907320e8680c507fffc6066}.png' not found 
on input line 6139.

! Unable to load picture or PDF file '_images/d44026c69907320e8680c507fffc6066.
png'.
<to be read again> 
                   }
l.6139 ...s/d44026c69907320e8680c507fffc6066}.png}
```

**版本**
- 系统: Ubuntu 22.04
- texlive版本:2022
- gmt版本: 6.4.0

**为什么自己编译pdf文档**

为了解决https://github.com/gmt-china/GMT_docs/issues/806 中描述的问题

**为什么不用网页版**
本地打开速度更快，搜索关键词更快

**Comment by seisman** [comment]
检查一下 `_build/_images` 目录下是否有 `d44026c69907320e8680c507fffc6066.png` 这个文件？

**Comment by seisman** [comment]
目前手册 PDF 在 GitHub 服务器上可以正常编译，所以这个问题无法复现。

**Comment by zhong-yy** [comment]
不好意思，之前忘记回复了。在gmt目录下只有build文件夹，没有_build。
![image](https://github.com/gmt-china/GMT_docs/assets/38816011/e6058fb1-db6e-47af-8ec1-2a4643aa1dd5)

build下面有个latex文件夹
![image](https://github.com/gmt-china/GMT_docs/assets/38816011/5a85857c-4ac2-4276-99bb-6d94634aeea1)


latex文件夹下面没有_images文件夹。`d44026c69907320e8680c507fffc6066.pdf`位于latex文件夹中，没有对应的`d44026c69907320e8680c507fffc6066.png`文件

**Comment by ZMAlt** [comment]
时间太久了，可能大家也都很久没有编译过了，尤其是 pdf，需要安装巨大的 TeXlive。

**Comment by seisman** [comment]
`d44026c69907320e8680c507fffc6066.png` 对应的是
![image](https://github.com/gmt-china/GMT_docs/assets/3974108/e2e22b71-43a0-4220-9bc6-afb7a8e40ac6)

这个文件应该不会存在问题。需要检查 make `latexpdf` 的一开始是否有警告信息。
