### ISSUE TITLE
等值线的标注

### ISSUE THREAD

**Issue by seisman** [gmt-china/GMT_docs#11]
http://gmt.soest.hawaii.edu/doc/latest/GMT_Docs.html#annotation-of-contours-and-quoted-lines

**Comment by jingxu002** [comment]
曾经为了画图，仔细看过这一部分内容，希望能参与翻译，如何加入？

**Comment by wangliang1989** [comment]
236099941 qq群

**Comment by seisman** [comment]
Finished in #41
