### ISSUE TITLE
[REVIEW] 审核/整理/更新“贡献者列表”

### ISSUE THREAD

**Issue by seisman** [gmt-china/GMT_docs#1129]
目前指向 https://github.com/gmt-china/GMT_docs/graphs/contributors

**Comment by seisman** [comment]
@all-contributors please add @seisman for ideas

**Comment by seisman** [comment]
@allcontributors please add @seisman for ideas, maintenance, bug, doc, example, review, data, design.

**Comment by seisman** [comment]
@allcontributors please add @seisman for ideas

**Comment by seisman** [comment]
@allcontributors please add @seisman for ideas, maintenance, bug, doc, example, review, data, design.

**Comment by seisman** [comment]
@allcontributors please add @seisman for maintenance, bug, doc, example, review, data, design.

**Comment by seisman** [comment]
@allcontributors please add @seisman for ideas

**Comment by seisman** [comment]
综合 https://github.com/gmt-china/GMT_docs/issues/450#issuecomment-867390050 的建议，现计划采用 [All Contributors](https://allcontributors.org/) 来显示每个贡献者的贡献。

PR https://github.com/gmt-china/GMT_docs/pull/1148 中，把我自己列为了贡献者，目前的贡献类型包括：

| Emoji | 类型 | 说明 |
|---|---|---|
| 🐛 | bug | 报告 Bug |
| 🔣 | data | 整理数据 |
| 📖 | doc | 撰写文档 |
| 🎨 | design | 网页设计 |
| 💡 | example | 增添示例 |
| 🤔 | ideas | 建议与想法 |
| 🚧 | maintenance | 底层维护 |
| 👀 | review | 审核文档 |
| 📹 | video | 录制视频教程 |

更多的贡献类型以及更多的贡献者将会在后面进一步添加

**Comment by seisman** [comment]
@allcontributors please add @core-man for bug, data, doc, design, ideas, review

**Comment by seisman** [comment]
@allcontributors please add @CovMat for bug, doc, example, review, video.

**Comment by seisman** [comment]
@allcontributors please add @core-man for bug, data, doc, design, ideas, review

**Comment by seisman** [comment]
@allcontributors please add @ZMAlt for doc, review, example, ideas

**Comment by seisman** [comment]
@allcontributors please add @wangliang1989 for example, ideas

**Comment by seisman** [comment]
@gmt-china/contributors I've added a few contributors to the README file. It would be great if someone can help me add more contributors (https://github.com/gmt-china/GMT_docs/graphs/contributors) and their contributions.

**Comment by wangliang1989** [comment]
Maybe, we can search the git history to find all contributors

**Comment by seisman** [comment]
> Maybe, we can search the git history to find all contributors

I think it's the same as https://github.com/gmt-china/GMT_docs/graphs/contributors.

The command `git shortlog -sne` shows:
```
  1636  Dongdong Tian <seisman.info@gmail.com>
   129  Xiaohan Chen <26203721+CovMat@users.noreply.github.com>
   123  Yao Jiayuan <coreman.seism@gmail.com>
    53  dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
    50  王亮 <wangliang0222@gmail.com>
    38  Mao Zhou <maozhou@whu.edu.cn>
    35  Mao Zhou <1831326353@qq.com>
    19  sqdeng <dengshanquan14@mails.ucas.edu.cn>
    16  赵志远 <shetu2008@163.com>
     9  liuzhumei <zhumei.liu.gucas@gmail.com>
     7  jingxu <jingxu@localhost.localdomain>
     7  lxrat <lixianrui1988@126.com>
     5  allcontributors[bot] <46447321+allcontributors[bot]@users.noreply.github.com>
     4  Fei Chen <Ohaiyo_fei@163.com>
     3  Xiao Xiao <2013301140017@whu.edu.cn>
     3  sqdeng <shanquandeng@163.com>
     2  Liming Li <32346042+cugliming@users.noreply.github.com>
     2  Xiao-Le Deng <xldeng@whu.edu.cn>
     2  dihuizhe <51852716+dihuizhe@users.noreply.github.com>
     1  Bojun <30320251+BerginJay@users.noreply.github.com>
     1  H.F <JiangXL@users.noreply.github.com>
     1  Jiayuan Yao <coreman.seism@gmail.com>
     1  PeterPanwl <wangliang0222@gmail.com>
     1  Tche LIU <seistche@gmail.com>
     1  Tche Liu <seistche@gmail.com>
     1  Yuechu Wu <12131066@mail.sustech.edu.cn>
     1  wangliang <wangliang0222@gmail.com>
```

**Comment by wangliang1989** [comment]
We need to use email address to distinguish different contributors instead of their name.
What's the next we should do?

**Comment by wangliang1989** [comment]
must discuss in English here？

**Comment by seisman** [comment]
需要做的事情包括
1. 确定贡献有哪些类型
2. 确认每个人做了哪类的贡献

**Comment by seisman** [comment]
@allcontributors please add @ZMAlt for bug, review

**Comment by seisman** [comment]
@allcontributors please add @wangliang1989 for doc, review

**Comment by seisman** [comment]
@allcontributors please add @sqdeng for example

**Comment by wangliang1989** [comment]
what can you do? @allcontributors

**Comment by seisman** [comment]
> what can you do? @allcontributors

参考：https://allcontributors.org/docs/en/bot/usage#commands

**Comment by seisman** [comment]
@allcontributors 
please add @zhaozhiyuan1989 for bug
please add @liuzhumei for bug, example
please add @ohaiyofei for bug
please add @SeisPider for example
please add @TcheL for bug
please add @lxrat for bug
please add @cugliming for doc
please add @xiaoledeng for bug
please add @dihuizhe for bug
please add @SeisPiano for doc
please add @JiangXL for bug
please add @BerginJay for bug

**Comment by seisman** [comment]
@allcontributors 
please add @zhaozhiyuan1989 for bug
please add @liuzhumei for bug, example
please add @ohaiyofei for bug
please add @SeisPider for example
please add @TcheL for bug
please add @lxrat for bug
please add @cugliming for doc
please add @xiaoledeng for bug
please add @dihuizhe for bug
please add @SeisPiano for doc
please add @JiangXL for bug
please add @BerginJay for bug

**Comment by seisman** [comment]
@allcontributors
please add @liuzhumei for bug, example.
please add @ohaiyofei for bug.
please add @SeisPider for example.
please add @TcheL for bug.
please add @lxrat for bug.
please add @cugliming for doc.
please add @xiaoledeng for bug.
please add @dihuizhe for bug.
please add @SeisPiano for doc.
please add @JiangXL for bug.
please add @BerginJay for bug.

**Comment by seisman** [comment]
@allcontributors please add @liuzhumei for bug, example.

**Comment by seisman** [comment]
please add @liuzhumei for bug, example.

**Comment by seisman** [comment]
@allcontributors please add @liuzhumei for bug, example.

**Comment by seisman** [comment]
@allcontributors please add @lxrat for bug.

**Comment by seisman** [comment]
@allcontributors please add @cugliming for doc.

**Comment by seisman** [comment]
@allcontributors please add @xiaoledeng for bug.

**Comment by seisman** [comment]
@allcontributors please add @dihuizhe for bug.

**Comment by seisman** [comment]
@allcontributors please add @SeisPiano for doc.

**Comment by seisman** [comment]
@allcontributors please add @JiangXL for bug.

**Comment by seisman** [comment]
@allcontributors please add @BerginJay for bug.

**Comment by seisman** [comment]
All done.
