### ISSUE TITLE
删除关于“GMT 远程数据”的详细介绍

### ISSUE THREAD

**Issue by seisman** [gmt-china/GMT_docs#1235]
在“地学数据”一章中，我们对每个 GMT 远程数据（https://docs.gmt-china.org/latest/dataset/#id2 ）都做了介绍，如https://docs.gmt-china.org/latest/dataset/earth-relief/，https://docs.gmt-china.org/latest/dataset/earth-age/ 。这些内容翻译整理自 https://www.generic-mapping-tools.org/remote-datasets/ ，但部分内容已经过时。这些内容中，对用户真正有用的信息包括：

1. GMT 提供了哪些远程数据
2. 远程数据如何使用
3. 每个远程数据提供了哪些精度和配准方式
4. 远程数据默认的 CPT（也许用户不关心）

因而，翻译和维护全部内容没太多意义。所以我建议

- [x] 删除所有关于 GMT 远程数据的详细介绍 https://github.com/gmt-china/GMT_docs/pull/1236
- [ ]  新增单独的一节，介绍 GMT提供了哪些远程数据（一个表格即可），使用方法（ `earth_relief_01d_g`）。至于每个数据有哪些精度和配准方式，用户直接阅读原始文档即可
- [x] 图库（https://docs.gmt-china.org/latest/gallery/） 中直接使用官方网站里的图片，并链接到官方网站。 https://github.com/gmt-china/GMT_docs/pull/1238

@gmt-china/contributors

**Comment by ZMAlt** [comment]
我同意。我看到最近 gmt 似乎在增加数据，上面这些可以减小我们负担

**Comment by ZMAlt** [comment]
现在地学数据集 https://docs.gmt-china.org/latest/dataset/ 这一章结构不是很合理。是不是可以仿照 GMT 官方的结构。

- GMT 数据集
    * 远程数据 （上面的第二条可以放到这里）
    * GSHHG
    * DCW
- 全球地学数据集
    * GADM
    * PB2002
    * global tectonics
    * WSM 2016

**Comment by seisman** [comment]
可以，我倾向于把远程数据放在 DCW 数据的后面，即 GSHHG -> DCW -> 远程数据

**Comment by ZMAlt** [comment]
嗯。如果你暂时没有计划的，我最近可以试试。

**Comment by seisman** [comment]
OK
