### ISSUE TITLE
换行导致多余的空格

### ISSUE THREAD

**Issue by ZMAlt** [gmt-china/GMT_docs#1335]
不知道从哪个版本开始，换行会导致一个空格，虽然也没什么大问题，暂时先记录一下。

**Comment by seisman** [comment]
你是指网页版？

**Comment by seisman** [comment]
https://github.com/gmt-china/GMT_docs/commit/a1933bae83fc7d96148b2d250653cca3070e821b

**Comment by ZMAlt** [comment]
是的，网页版。我看现在仍然是这种情况。

**Comment by seisman** [comment]
这是 ReStructuredText 语言在写中文文档时都会遇到的问题，之前我们使用了 sphinx-cjkspace 插件解决了这个问题，在 a1933bae83fc7d96148b2d250653cca3070e821b 里我删除了这个插件，但我忘了我为什么要删除了

**Comment by ZMAlt** [comment]
那就暂时关闭吧。
