### ISSUE TITLE
inset的中文翻译

### ISSUE THREAD

**Issue by seisman** [gmt-china/GMT_docs#1338]
目前手册里翻译成图中图，有人反馈正确的翻译应该是区位图

**Comment by ZMAlt** [comment]
即使图中图不合适，我认为也不应该用区位图，我从这个名字都看不出是什么意思。反而图中图用的多了，大家都已经知道它的含义了。Inset 可以是一个放大细节图，也可以是一个缩小的显示位置的图， 而且从 inset 的意思来看，“图中图” 也比较合适。

**Comment by seisman** [comment]
那就在介绍里加一句:图中图，也称之为区位图
