### ISSUE TITLE
GMT多版本切换

### ISSUE THREAD

**Issue by seisman** [gmt-china/GMT_docs#14]
http://gmt.soest.hawaii.edu/doc/latest/GMT_Docs.html#switching-between-different-gmt-versions

**Comment by liuzhumei** [comment]
我这两天试了一下切换，发现windows用户并不适合按照上述方式，不仅需要额外安装不稳定工具，还非常麻烦，还是seisman提到的“删软链接”法安全便捷有效。由于不懂linux，因此如何取消这个Assigne？
