### ISSUE TITLE
增加“如何修改GMT参数”的入门教程

### ISSUE THREAD

**Issue by seisman** [gmt-china/GMT_docs#167]

**Comment by core-man** [comment]
@wangliang1989 在 #180 中解决此 issue？

**Comment by wangliang1989** [comment]
> @wangliang1989 在 #180 中解决此 issue？

之前seisman说他对我交的pr还有不满意的地方，等他修改后再merge

**Comment by core-man** [comment]
> > @wangliang1989 在 #180 中解决此 issue？
> 
> 之前seisman说他对我交的pr还有不满意的地方，等他修改后再merge。但是 @seisman 一直没修改

Okay. 这个 issue 和 PR 的优先级并不是最高的目前，慢慢磨一个优秀的 tutorial 也好。

**Comment by wangliang1989** [comment]
> > > @wangliang1989 在 #180 中解决此 issue？
> > 
> > 
> > 之前seisman说他对我交的pr还有不满意的地方，等他修改后再merge。但是 @seisman 一直没修改
> 
> Okay. 这个 issue 和 PR 的优先级并不是最高的目前，慢慢磨一个优秀的 tutorial 也好。

可能写了5年了，哈哈哈 我记忆里是16年就是说缺一个入门教程。其实现在这个也可以了
