### ISSUE TITLE
中文手册网站无法访问

### ISSUE THREAD

**Issue by kanglcn** [gmt-china/GMT_docs#181]
如题。

**Comment by seisman** [comment]
请 ping docs.gmt-china.org 确认是否可以 ping 通

**Comment by kanglcn** [comment]
可以 ping 通，另外，gmt-china.org 可以正常访问，doc.gmt-china.org 不可以。

**Comment by seisman** [comment]
docs.gmt-china.org 的网页内容目前分别托管在GitHub和Coding服务器上。默认国际用户访问github服务器，国内用户访问coding服务器。

GitHub IP: 185.199.109.153
Coding IP: 124.156.205.241

请确认你 ping 返回的地址是哪一个。如果是coding的IP，你可以尝试修改HOST将 docs.gmt-china.org 强制指向  GitHub IP.

**Comment by kanglcn** [comment]
我在国内。
ping gmt-china.org 返回的地址是GItHub的IP: 185.199.109.153;
ping docs.gmt-china.org 返回的地址是Coding的IP，但是不是你所说的，而是124.156.193.111.
按你说的修改host将 docs.gmt-china.org 强制指向GItHub的IP: 185.199.109.153之后可以正常访问docs.gmt-china.org。
谢谢。
