### ISSUE TITLE
完善地学数据集

### ISSUE THREAD

**Issue by wangliang1989** [gmt-china/GMT_docs#184]
目前，相较于官方手册，中文手册没有介绍 Global Earth Mask Grids 和 Global Earth Day/Night Images。我不清楚这二者的准确中文名称

**Comment by wangliang1989** [comment]
目前在地形数据中说明了地形数据绘图的一些基本原理，就是从GMT服务器下载数据画图这些。影像数据也是这样子，应该是没有必要把这些原理又讲一遍。

我觉得有两个办法，一个是只在数据库原理解释，删除地形数据小节里面的原理部分。另一个是影像数据中说原理和地形数据一样，其余保留原样
@seisman

**Comment by seisman** [comment]
我目前还没有想好如何处理。目前数据分为三类：

1. GMT提供的需要安装的数据：GSHHG和DCW数据
2. GMT提供的需要自动下载的数据：earth_relief, earth_image 等
3. 其它与GMT无关的数据: GADM 等

**Comment by wangliang1989** [comment]
我觉得可能需要把上面这个分类放进overview，清楚交代给读者。
至于需要下载的数据，earth_relief 和 earth_image 两个原理完全一样，是否需要在这两部分详细地把同样的内容说两遍？

**Comment by seisman** [comment]
相同的部分肯定不需要再介绍了。

**Comment by wangliang1989** [comment]
在overview里面介绍原理。
在各个数据的章节里，只按照使用方法，大概说一下。比如地形数据，就说这个属于gmt自动下载那一类就完了。

**Comment by seisman** [comment]
可以。
