### ISSUE TITLE
Mac 安装相关信息需要更新

### ISSUE THREAD

**Issue by wangliang1989** [gmt-china/GMT_docs#225]
在第一次运行gmt的时候，Mac会提示安全警示。
Mac在Catalina之后zsh是默认shell，似乎gmt官方不知道这一点

**Comment by seisman** [comment]
> 在第一次运行gmt的时候，Mac会提示安全警示。

大多数 mac 软件都有这个问题，没办法，用户自己遇到几次就知道了。

> Mac在Catalina之后zsh是默认shell，似乎gmt官方不知道这一点

哪里有提到 bash 和 zsh?

**Comment by wangliang1989** [comment]
你可以搜一下，从Catalina开始，Mac的默认shell是zsh了。我今天装了gmt，安装后，gmt在shell里输出说添加环境变量只支持bash，似乎你用的zsh。

**Comment by seisman** [comment]
> 你可以搜一下，从Catalina开始，Mac的默认shell是zsh了。

我知道，这一点没有问题。

> 安装后，gmt在shell里输出说添加环境变量只支持bash，似乎你用的zsh。

GMT 应该没有这么说过。

**Comment by wangliang1989** [comment]
我之前也没有看见过，今天在arm上安装第一次见到

**Comment by seisman** [comment]
提供截图
