### ISSUE TITLE
示例测试工具

### ISSUE THREAD

**Issue by seisman** [gmt-china/GMT_docs#23]
目前文档中有很多示例，某些示例是以脚本的形式给出的，这种示例可以直接运行以进行测试。而某些示例是直接以单行代码的形式出现在文档中的，这些示例在最初是经过测试的，但是一旦GMT版本有更新，这些示例能否正常运行则无法确认。

两种解决办法：
1. 所有示例均写到脚本中，不管是一行还是两行
2. 写一个单独的脚本，搜索文档中的所有示例，然后依次执行这些示例

**Comment by PeterPanwl** [comment]
方案2如何实现？

**Comment by seisman** [comment]
两种可能的实现方式，一种是根据示例在文件中的特征，通过类似正则表达式来判断哪些语句属于示例，然后直接执行即可。另一种可能的实现方式是直接调用比较成熟的rst语言解析工具，然别的工具来解析rst文件，然后自己再写代码处理其中的code语句。

**Comment by PeterPanwl** [comment]
显然1简洁

**Comment by seisman** [comment]
1相当于自己完成一个简易版的rst语言解析工具，并不一定比2简单。

**Comment by PeterPanwl** [comment]
既然已经写了脚本了，去执行脚本就是，分析rst干啥

**Comment by seisman** [comment]
GMT_Docs中的大部分示例都是直接写在文档中的，并没有写到脚本中。

**Comment by seisman** [comment]
Closed by #94
