### ISSUE TITLE
Improve the sidebar for Get Started

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#234]
Here are some suggestions for the [入门教程](https://docs.gmt-china.org/latest/tutorial/) sections:
- [x] How about changing the order of [理解图层](https://docs.gmt-china.org/latest/tutorial/layers/) and [绘制直方图](https://docs.gmt-china.org/latest/tutorial/histogram/)? I feel the concept of layering should be the last tutorial.
~~- [ ] How about adding a new section in GMT 入门 (e.g., 绘图模式) and move [GMT单行模式](https://docs.gmt-china.org/latest/tutorial/oneliner/), [GMT图中图模式](https://docs.gmt-china.org/latest/tutorial/inset/), [GMT子图模式](https://docs.gmt-china.org/latest/tutorial/subplot/) and [GMT多图模式](https://docs.gmt-china.org/latest/tutorial/multifig/) there ? I feel new GMT users won't need to learn those four sections until they really have to plot inset and multiple subfigs.~~
~~- [ ] [绘制直方图](https://docs.gmt-china.org/latest/tutorial/histogram/) is great, but I think it's better to put it in another place cause most new GMT users don't need to plot a histogram, right? However, it seems there is no better section to include it. How about adding a new section in GMT 进阶 (e.g., 进阶教程)? #180 is also an advanced tutorial.~~

**Comment by seisman** [comment]
> 1. How about changing the order of [理解图层](https://docs.gmt-china.org/latest/tutorial/layers/) and [绘制直方图](https://docs.gmt-china.org/latest/tutorial/histogram/)? I feel the concept of layering should be the last tutorial.

Yes.

**Comment by core-man** [comment]
> 2. How about adding a new section in GMT 入门 (e.g., 绘图模式) and move [GMT单行模式](https://docs.gmt-china.org/latest/tutorial/oneliner/), [GMT图中图模式](https://docs.gmt-china.org/latest/tutorial/inset/), [GMT子图模式](https://docs.gmt-china.org/latest/tutorial/subplot/) and [GMT多图模式](https://docs.gmt-china.org/latest/tutorial/multifig/) there ? I feel new GMT users won't need to learn those four sections until they really have to plot inset and multiple subfigs.

The new section should be within `GMT 进阶`.

**Comment by seisman** [comment]
> > 1. How about adding a new section in GMT 入门 (e.g., 绘图模式) and move [GMT单行模式](https://docs.gmt-china.org/latest/tutorial/oneliner/), [GMT图中图模式](https://docs.gmt-china.org/latest/tutorial/inset/), [GMT子图模式](https://docs.gmt-china.org/latest/tutorial/subplot/) and [GMT多图模式](https://docs.gmt-china.org/latest/tutorial/multifig/) there ? I feel new GMT users won't need to learn those four sections until they really have to plot inset and multiple subfigs.
> 
> The new section should be within `GMT 进阶`.

中文手册目前的设计逻辑不是这样的。"GMT进阶"中包含了官方cookbook里的内容，是作为参考书存在的，与“入门教程”的目的是完全不同的。

**Comment by core-man** [comment]
我理解的入门教程是新手必须要一开始就学的，还是你想包括一些高级教学（如直方图和配置参数设置）？

可否在GMT入门里开设两个教程，一个是入门级别的，一个是高级教程。这样或许有助于新手快速搞定入门教程，建立信心和感觉。

**Comment by core-man** [comment]
建议把部分内容放到**入门教程**外面，这样会有层次和重点，有助于初学者安排时间学习。比如，

> 2. How about adding a new section in GMT 入门 (e.g., 绘图模式) and move [GMT单行模式](https://docs.gmt-china.org/latest/tutorial/oneliner/), [GMT图中图模式](https://docs.gmt-china.org/latest/tutorial/inset/), [GMT子图模式](https://docs.gmt-china.org/latest/tutorial/subplot/) and [GMT多图模式](https://docs.gmt-china.org/latest/tutorial/multifig/) there ? I feel new GMT users won't need to learn those four sections until they really have to plot inset and multiple subfigs.

**Comment by seisman** [comment]
或许可以在教程里分入门教程和进阶教程

**Comment by core-man** [comment]
我觉得入门教程还是现在的Level 1级别比较好，即总是显示在目录第一级。

**Comment by seisman** [comment]
当教程增加的时候，左边栏就会变得太长了

**Comment by core-man** [comment]
现在其实只需要增加进阶教程，然后把绘图模式、直方图、配置参数设置移动过去？

此外，GMT进阶段其实还需要好好设置，感觉Level 1的目录太多了，我回头再想想进阶如何改善分级。

**Comment by core-man** [comment]
- 入门教程
  - GMT初探
  - 命令初探
  - ...
  - 添加图例
  - 绘制地形起伏
  - 理解图层
- 进阶教程
  - 绘制直方图
  - GMT单行模式
  - ...
  - GMT多图模式

---

- [入门教程](https://docs.gmt-china.org/latest/tutorial/):
  - 初级：同上
  - 进阶：同上

@seisman Which one do you prefer? or You have a better suggestion?

**Comment by wangliang1989** [comment]
> It seems that we could have the following two layouts:
> 
> * 入门教程
>   
>   * GMT初探
>   * 命令初探
>   * ...
>   * 添加图例
>   * 绘制地形起伏
>   * 理解图层
> * 进阶教程
>   
>   * 绘制直方图
>   * GMT单行模式
>   * ...
>   * GMT多图模式
> 
> * [入门教程](https://docs.gmt-china.org/latest/tutorial/):
>   
>   * 初级：同上**入门教程**
>   * 进阶：同上**进阶教程**
> 
> @wangliang1989 @seisman Which one do you prefer? or You have a better suggestion?

保持原样

如果要改变的话，那新的进阶教程是什么呢

**Comment by core-man** [comment]
我还是觉得入门教程太长了，
入门教程:
- **初级:**  最基本、常用的 GMT入门教程，如底图、海岸线... 符号、文字
- **中级:** 想对较难一点入门教程，如图例、地形起伏、直方图、图层
