### ISSUE TITLE
Improve CONTIBUTING.md

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#236]
[CONTRIBUTING.md](https://github.com/gmt-china/GMT_docs/blob/master/CONTRIBUTING.md) was updated on Aug 8, 2020. Shall we polish it based on our experience in [seismo-learn](https://github.com/seismo-learn) and [PyGMT](https://github.com/GenericMappingTools/pygmt)? Do we want to include it in the documentation or still in the repo?

**Comment by seisman** [comment]
Yes, it should be moved to the documentation.

**Comment by core-man** [comment]
Also https://github.com/gmt-china/GMT_docs/pull/321#issuecomment-849286273
