### ISSUE TITLE
Generate teams

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#237]
Shall we generate some teams, e.g., admin and contributions, so that we may know our permission and responsibility?

**Comment by seisman** [comment]
This is a small team, with very few contributors. So perhaps not necessary?

**Comment by core-man** [comment]
It seems that we have nine members. We may have more and more contributors.

**Comment by seisman** [comment]
They're all inactive.

**Comment by core-man** [comment]
who are active？

**Comment by core-man** [comment]
Maybe you could submit a few issues so that I can help or make some comments.

**Comment by core-man** [comment]
I still suggest to have some teams which looks official.

**Comment by seisman** [comment]
OK. i will create teams later and open some good first issues.

**Comment by seisman** [comment]
Done.
