### ISSUE TITLE
更新 grdtrend  页面的数学公式

### ISSUE THREAD

**Issue by seisman** [gmt-china/GMT_docs#238]
https://docs.gmt-china.org/latest/module/grdtrend/

![image](https://user-images.githubusercontent.com/3974108/115076296-5dd8be00-9eca-11eb-82f4-97b9c689fa14.png)

可以用 `.. math::` 指令以及 LaTeX 语法重写这个公式。

官方文档也有一样的问题 (https://docs.generic-mapping-tools.org/dev/grdtrend.html )，因而也可以对官方文档做同样的修改。

**Comment by core-man** [comment]
I reopen it so that I won't forget to submit a similar PR to GMT.
