### ISSUE TITLE
GMT的中文支持

### ISSUE THREAD

**Issue by seisman** [gmt-china/GMT_docs#24]
参考：
1. https://seisman.info/gmt-chinese-support-under-windows.html
2. https://seisman.info/gmt-chinese-under-linux.html

**Comment by PeterPanwl** [comment]
这个就是seisman博客里那个gmt中文支持？写在哪里呢？

**Comment by seisman** [comment]
可以整理到附录

**Comment by PeterPanwl** [comment]
我准备做，以master为基础建立分支吗？

**Comment by seisman** [comment]
YES
