### ISSUE TITLE
Simplify makefile

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#252]
I feel the [makefile](https://github.com/gmt-china/GMT_docs/blob/master/Makefile) is not good for new contributors. Please see the makefiles in [PyGMT](https://github.com/GenericMappingTools/pygmt/blob/master/doc/Makefile) and [seismo-learn/seismoloy101](https://github.com/seismo-learn/seismology101/blob/main/Makefile).

**Comment by seisman** [comment]
I can't see how the makefile can be simplified. The Makefile is longer since it builds both HTML and PDF formats.
