### ISSUE TITLE
Move the appendix to the documentation

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#253]
We have three tutorials in the appendix, which should be moved into the documentation:
- [环境变量](https://docs.gmt-china.org/latest/appendix/variables/)
- [目录参数](https://docs.gmt-china.org/latest/appendix/special-dirs/)
- [等值线标注和“线条标注”](https://docs.gmt-china.org/latest/appendix/contour-annot/)

Currently, we can put them in [入门教程](https://docs.gmt-china.org/latest/tutorial/) until we have a new sidebar (#234)., although [GMT基础/输入文件的搜索目录](https://docs.gmt-china.org/latest/basis/input-files/#) is somehow related to [环境变量](https://docs.gmt-china.org/latest/appendix/variables/) and [目录参数](https://docs.gmt-china.org/latest/appendix/special-dirs/).

**Comment by seisman** [comment]
They are not tutorials.

**Comment by core-man** [comment]
我还是强烈建议把三个移动其他地方，移动到 **GMT 进阶** 也好。

**Comment by seisman** [comment]
这三节放在这里纯粹是因为不知道放哪合适。

**Comment by core-man** [comment]
那我们暂时保持这个issue open状态，直到找到合适的位置吧。

**Comment by core-man** [comment]
我目前的看法时：环境变量和目录参数暂时放在附录下，同时上一级目录重命名为**GMT 目录**；等值线标注和“线条标注”移动到 **GMT**基础里。

**Comment by core-man** [comment]
我接下来会参考 GMT 官方手册，先将**环境变量**和**目录参数**两节内容移动到手册正文：

- https://docs.generic-mapping-tools.org/6.1/gmt.conf.html#dir-parameters
- https://docs.generic-mapping-tools.org/6.1/cookbook/features.html#directory-parameters

- [ ] 更新 [DIR 参数](https://docs.gmt-china.org/latest/conf/dir/)：#350

**Comment by core-man** [comment]
[等值线标注和“线条标注”](https://docs.gmt-china.org/latest/appendix/contour-annot/)中既有部分基础内容，又有大量的实例。因此我们是否暂时把它移动到新增的**GMT实例**章节中呢？

**Comment by seisman** [comment]
> [等值线标注和“线条标注”](https://docs.gmt-china.org/latest/contour-annot/)中既有部分基础内容，又有大量的实例。因此我们是否暂时把它移动到新增的**GMT实例**章节中呢？ Ping @seisman for comments.
> 
> 源文件也直接位于 `source` 目录下：[https://github.com/gmt-china/GMT_docs/blob/master/source/contour-annot.rst](https://github.com/gmt-china/GMT_docs/blob/master/source/contour-annot.rst?rgh-link-date=2021-06-24T09%3A24%3A09Z)

这一节介绍了太多内容，不适合作为实例。

**Comment by core-man** [comment]
实际上我们遇到了一个既不是tutorial，又不是实例的。然后也不是 GMT 基础。

**Comment by seisman** [comment]
其实可能放在 grdcontour 里更合适。

**Comment by core-man** [comment]
> grdcontour

这么长的例子吗？ :smile:

**Comment by seisman** [comment]
@core-man 我建议关闭这个 issue，并重新开一个issue，解释清楚需要做什么。这样大家更可能会去做。

**Comment by core-man** [comment]
> @core-man 我建议关闭这个 issue，并重新开一个issue，解释清楚需要做什么。这样大家更可能会去做。

okay，will do it.tomorrow.
