### ISSUE TITLE
Improve the menu link

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#254]
See the menu links:
![menu links](https://user-images.githubusercontent.com/50591376/115139806-99a88a80-a066-11eb-9377-c5e64db13dd0.png)

We won't have 贡献指南 after #251 is approved (b7d818928c6adb5e6d07d7d7d26e7443db155a69), and **联系我们** does not work. So, how about changing the order to be:

- GMT 中文社区
- 手册源码
- PDF 手册
- [参与讨论](https://github.com/gmt-china/GMT_docs/discussions)

**Comment by seisman** [comment]
Sounds good.
