### ISSUE TITLE
将版本迁移移动到安装下？

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#271]
- 版本迁移并不值得放在Level 1
- GMT4-GMT5, GMT5-GMT6，经典-现代三个章节可以合并成一个文件

**Comment by seisman** [comment]
> 将版本迁移移动到安装下？

版本迁移与安装无关

> 版本迁移并不值得放在Level 1

版本迁移放在 level 1，本质上是让老用户了解迁移成本，鼓励他们使用新版本

> GMT4-GMT5, GMT5-GMT6，经典-现代三个章节可以合并成一个文件

可以试试看效果如何

**Comment by core-man** [comment]
> > GMT4-GMT5, GMT5-GMT6，经典-现代三个章节可以合并成一个文件
> 
> 可以试试看效果如何

Will try it.

**Comment by seisman** [comment]
考虑了一下，没必要将三节合并为一个文件。原因如下：

1. 合并之后这一节内容太多
2. 这三节的受众是GMT老用户。老用户只需要根据自己的需求读一节即可，而不需要三节都读
