### ISSUE TITLE
Use sphinx-panels?

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#272]
https://sphinx-panels.readthedocs.io/en/latest/

**Comment by seisman** [comment]
Unclear to me where we should use it.

**Comment by core-man** [comment]
Maybe new contributing guidelines to install `git` on different OS.

**Comment by seisman** [comment]
> Maybe new contributing guidelines to install `git` on different OS.

We will refer readers to other online resources (e.g., seismo-learn) instead.

**Comment by core-man** [comment]
> > Maybe new contributing guidelines to install `git` on different OS.
> 
> We will refer readers to other online resources (e.g., seismo-learn) instead.

Okay.
