### ISSUE TITLE
Build PDF using TinyTex

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#273]
@seisman is working on a GitHub Actions workflow in #264. In that PR, we use TinyTex to build the PDF, but [构建文档](https://docs.gmt-china.org/latest/contributing/#id3) still recommends TexLive. We should recommend TinyTex.

**Comment by seisman** [comment]
No, we use TinyTeX only because it's smaller and faster for CI purpose.

For most users, they should use TeXLive unless they're LaTeX gurus.
