### ISSUE TITLE
「GMT中文演示效果」一节需要修改

### ISSUE THREAD

**Issue by wangliang1989** [gmt-china/GMT_docs#286]
该节的「注解」中说“我。。。”，这不是手册的语言风格。而且我自己这里是找不到这个文件的“share/localization/gmt_cn1.locale”这个文件的

**Comment by seisman** [comment]
> 该节的「注解」中说“我。。。”，这不是手册的语言风格。

I agree. Please fix it if you want.

> 而且我自己这里是找不到这个文件的“share/localization/gmt_cn1.locale”这个文件的

Run `gmt --show-sharedir` to find the path of your share directory. This file should be in that directory.
