### ISSUE TITLE
手册的反馈评论方法

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#295]
当前手册允许评论功能，比如 https://docs.gmt-china.org/6.0/ 。文档初始，此功能方便用户反馈和帮助解决问题。目前存在以下问题：

- 造成了一定程度的文档臃肿
- 大多数中文用户选择在 QQ 群问问题，少有人使用 GitHub

因此，我们需要考虑更好的用户反馈和评论的方式，目前主要选择（可以多选）有：

1.  使用 QQ 群（当前使用中）：

     优点：国内用户最多、较易于发表评论、及时通讯
     缺点：嘈杂、不易并行处理不同问题、讨论历史很难追踪

2.  使用 gitalk 功能（当前使用中）

     优点：与文档相关的问题显示可见
     缺点：造成文档臃肿、国内用户较少

3.  使用 GitHub Discussions 和 Issues（当前使用中，但用户极少）

     优点：与 GitHub 磨合度最好（如方便维护者和贡献者维护相关问题，不需要额外维护其他网站或 app）、讨论历史容易追踪
     缺点：国内用户较少、有时需要掌握科学上网技巧

4.   使用论坛（如 [GMT 官方论坛](https://forum.generic-mapping-tools.org/)，[ObsPy 论坛](https://discourse.obspy.org/)，[Fortran 论坛](https://fortran-lang.discourse.group/)）

     优点：较易于发表评论、方便分类
     缺点：嘈杂、讨论历史很难追踪

----

1.  我们需要确定是否需要取消 gitalk 功能；如果确定取消，需要考虑取消可能带来的问题，比如相关历史记录是否会丢掉。

2.  是否建议用户少用 QQ 提问？

3.  是否建议用户多使用 GitHub Discussions 和 Issues？

4.  是否使用论坛？

**Comment by seisman** [comment]
> 1. 我们需要确定是否需要取消 gitalk 功能；如果确定取消，需要考虑取消可能带来的问题，比如相关历史记录是否会丢掉。

使用 gitalk 的最初目的是为了方便用户反馈问题以改进文档，而不是用于提问与解答，所以历史评论无所谓。

> 2. 是否建议用户少用 QQ 提问？

难以做到。

> 3. 是否建议用户多使用 GitHub Discussions 和 Issues？

GitHub 在国内访问不畅

> 4. 是否使用论坛？

以前做过论坛，但用户很少，最终关闭了论坛。
