### ISSUE TITLE
其它地形起伏数据

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#300]
补充 https://blog.seisman.info/global-relief-models/ 中的部分内容至[其它地形起伏数据](https://docs.gmt-china.org/latest/dataset/earth-relief/#id5)小段

**Comment by seisman** [comment]
Sounds good to me.

**Comment by seisman** [comment]
还需要迁移吗？感觉基本都列出来了。其他的像 etopo5, etopo2 之类的太老了，而且精度也太低，没必要用。GTOPO 原始数据是分块的，用起来很麻烦，也没必要。

**Comment by core-man** [comment]
经纬度范围没有列出来，我还是想略微概括这些数据的要点。5和2没必要了

**Comment by seisman** [comment]
OK

**Comment by ZMAlt** [comment]
要添加海洋地形数据吗？

1. SIO V20.1 (仅海洋) ftp://topex.ucsd.edu/pub/global_topo_1min/topo_20.1.img
SIO 海深模型是 Smith 和 Sandwell 研制的（其实我并不知道模型应该叫什么名字，Smith 是 NOAA的，Sandwell 是 SIO的，这里采用 胡敏章博士 在论文中的称呼）。SIO 海深模型采用 img 格式，即球墨卡托投影，分辨率 1 分。可以使用 img2grd 提取数据。纬度范围约为 正负80 度。目前还在常规更新，最新版本为 V20.1

2. DTU18BAT (仅海洋) ftp://ftp.space.dtu.dk/pub/DTU18/1_MIN/DTU18BAT_1min.bat.gz
由丹麦科技大学 Andersen 团队研制。分辨率为 1 分。模型也在常规更新，最新模型版本为 DTU18BAT。

**Comment by core-man** [comment]
@ZMAlt 这里主要是想添加其他地形数据的链接、简介等。

> SIO V20.1 (仅海洋) ftp://topex.ucsd.edu/pub/global_topo_1min/topo_20.1.img

这个数据好像是很多数据的海水深度来源，比如 [SRTM30](https://blog.seisman.info/srtm30-plus/)。

> DTU18BAT (仅海洋) ftp://ftp.space.dtu.dk/pub/DTU18/1_MIN/DTU18BAT_1min.bat.gz

Good~

**Comment by seisman** [comment]
我又想了一下这个问题。GMT目前已经提供了全球15s，以及陆地03s和01s，对于GMT绘图而言已经完全足够了，而且对于绘图而言，不同地形模型之间的差异基本可以忽略。只有个别用户在涉及到地形相关的计算时才会在意地形数据的选择，而这部分用户显然比我们更懂地形。

所以我个人倾向于不整理更多的地形起伏数据。

**Comment by core-man** [comment]
这个issue级别很低，或许可以等专业用户认领

**Comment by seisman** [comment]
因为过于专业，对于一般 GMT 用户没用，所以也就没必要整理进去了。

**Comment by seisman** [comment]
我目前更倾向于把整个“其它地形起伏数据”删掉。

**Comment by core-man** [comment]
> 我又想了一下这个问题。GMT目前已经提供了全球15s，以及陆地03s和01s，对于GMT绘图而言已经完全足够了，而且对于绘图而言，不同地形模型之间的差异基本可以忽略。

是的，当前 GMT 官方提供的[地形数据](https://docs.gmt-china.org/latest/dataset/earth-relief/)已经足够绘图使用了：
- 15 弧秒的全球地形起伏也是全球模型最高精度了
- 01和03弧秒的地形起伏也是当前区域数据模型最好的精度了

我主要考虑的是用几句话概括和列出以下地形数据：
- [GEBCO](https://www.gebco.net/data_and_products/gridded_bathymetry_data/): 该数据也是全球尺度的，精度是 15 弧秒 (见[Find out more: GEBCO_2020 Grid](https://www.gebco.net/data_and_products/gridded_bathymetry_data/gebco_2020/))。
- [ASTER GDEM](https://lpdaac.usgs.gov/products/astgtmv003/)：该数据是区域数据 (纬度 [-83,83]，见 [New Version of the ASTER GDEM](https://earthdata.nasa.gov/learn/articles/new-aster-gdem))，1 弧秒精度

---

见 SeisMan 博客：https://blog.seisman.info/global-relief-models/
> - 对于全球尺度或者大尺度地形图来说，可以使用 etopo1 甚至 etopo5 数据；
> - 对于 3 度 *3度-10度*10 度的区域，可以使用 SRTM30_PLUS 数据；
> - 对于 3 度 *3 度以下的区域，可以使用 SRTM 或 ASTER GDEM 数字数据。

这个note是否可以写入[入门教程：绘制地形起伏](https://docs.gmt-china.org/latest/tutorial/earth-relief/)或者[地形起伏数据](https://docs.gmt-china.org/latest/dataset/earth-relief/).

**Comment by seisman** [comment]
> 我主要考虑的是用几句话概括和列出以下地形数据：
> 
> * [GEBCO](https://www.gebco.net/data_and_products/gridded_bathymetry_data/): 该数据也是全球尺度的，精度是 15 弧秒 (见[Find out more: GEBCO_2020 Grid](https://www.gebco.net/data_and_products/gridded_bathymetry_data/gebco_2020/))。
> * [ASTER GDEM](https://lpdaac.usgs.gov/products/astgtmv003/)：该数据是区域数据 (纬度 [-83,83]，见 [New Version of the ASTER GDEM](https://earthdata.nasa.gov/learn/articles/new-aster-gdem))，1 弧秒精度

这两套数据都和 GMT 提供的数据相当，所以为何还要提及这两套数据？

> 见 SeisMan 博客：[blog.seisman.info/global-relief-models](https://blog.seisman.info/global-relief-models/)
> 
> > * 对于全球尺度或者大尺度地形图来说，可以使用 etopo1 甚至 etopo5 数据；
> > * 对于 3 度 _3度-10度_10 度的区域，可以使用 SRTM30_PLUS 数据；
> > * 对于 3 度 *3 度以下的区域，可以使用 SRTM 或 ASTER GDEM 数字数据。
> 
> 这个note是否可以写入[入门教程：绘制地形起伏](https://docs.gmt-china.org/latest/tutorial/earth-relief/)或者[地形起伏数据](https://docs.gmt-china.org/latest/dataset/earth-relief/).

这个 note 可以写，事实上 GMT 正在计划支持自动选择分辨率，即给定 `@earth_relief` 时自动根据区域范围选择合适的分辨率，但是目前还没有实现。

**Comment by seisman** [comment]
> > 见 SeisMan 博客：[blog.seisman.info/global-relief-models](https://blog.seisman.info/global-relief-models/)
> > > * 对于全球尺度或者大尺度地形图来说，可以使用 etopo1 甚至 etopo5 数据；
> > > * 对于 3 度 _3度-10度_10 度的区域，可以使用 SRTM30_PLUS 数据；
> > > * 对于 3 度 *3 度以下的区域，可以使用 SRTM 或 ASTER GDEM 数字数据。
> > 
> > 
> > 这个note是否可以写入[入门教程：绘制地形起伏](https://docs.gmt-china.org/latest/tutorial/earth-relief/)或者[地形起伏数据](https://docs.gmt-china.org/latest/dataset/earth-relief/).
> 
> 这个 note 可以写，事实上 GMT 正在计划支持自动选择分辨率，即给定 `@earth_relief` 时自动根据区域范围选择合适的分辨率，但是目前还没有实现。

这个可以做一个测试，对于一张正常大小（15 cm）的图而言，不同大小的区域，选择怎样的数据分辨率是大家可以接受的。

**Comment by core-man** [comment]
> 这个可以做一个测试，对于一张正常大小（15 cm）的图而言，不同大小的区域，选择怎样的数据分辨率是大家可以接受的。

是的，是否写入教程？

**Comment by core-man** [comment]
> 这两套数据都和 GMT 提供的数据相当，所以为何还要提及这两套数据？

一来列表很简单，而来作为补充点也是可以的。

**Comment by seisman** [comment]
我是觉得没有必要，GMT用户完全不会用到这些数据。

**Comment by core-man** [comment]
> > 见 SeisMan 博客：[blog.seisman.info/global-relief-models](https://blog.seisman.info/global-relief-models/)
> > > * 对于全球尺度或者大尺度地形图来说，可以使用 etopo1 甚至 etopo5 数据；
> > > * 对于 3 度 _3度-10度_10 度的区域，可以使用 SRTM30_PLUS 数据；
> > > * 对于 3 度 *3 度以下的区域，可以使用 SRTM 或 ASTER GDEM 数字数据。
> > 
> > 
> > 这个note是否可以写入[入门教程：绘制地形起伏](https://docs.gmt-china.org/latest/tutorial/earth-relief/)或者[地形起伏数据](https://docs.gmt-china.org/latest/dataset/earth-relief/).
> 
> 这个 note 可以写，事实上 GMT 正在计划支持自动选择分辨率，即给定 `@earth_relief` 时自动根据区域范围选择合适的分辨率，但是目前还没有实现。

当前 issue 只要写以上一个较短的 note 即可。
