### ISSUE TITLE
中国地学数据集

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#301]
完善[中文手册：中国地学数据集](https://docs.gmt-china.org/latest/dataset-CN/)，即构建[China's Geospatial Data for GMT](https://github.com/gmt-china/china-geospatial-data)。计划按照以下流程：

- 首先可以将 GMT中文社区主页的相关数据(数据位于 https://github.com/gmt-china/gmt-china.org/tree/master/content/data) 先汇总、移动至**China's Geospatial Data for GMT**仓库
- 更新中文手册
- 迁移后，删除或更新社区网站中相应部分

迁移列表（暂定）：

- [ ] 中国地学数据：https://gmt-china.org/data/
- [ ] GMT自带中国国界问题：https://gmt-china.org/blog/china-border-issues/
- [ ] 中国国界、省界及十段线：https://gmt-china.org/example/ex003/
- [ ] More

移动中文社区图库至中文手册时（#302 ），也会涉及到地学数据的移动。

**Comment by wangliang1989** [comment]
目前，地学数据集有一个更急迫的问题：https://docs.gmt-china.org/latest/dataset-CN/CN_faults/ 这个页面的图都没有画出来。断层数据目前社区似乎有两个： https://raw.githubusercontent.com/gmt-china/china-geospatial-data/master/CN_faults.gmt 和https://gmt-china.org/data/CN-faults.dat

**Comment by CovMat** [comment]
我觉得就直接传图上去，不要让服务器画了
一张图也就几百KB，不会占很多

**Comment by wangliang1989** [comment]
我依然支持传代码

**Comment by core-man** [comment]
> 断层数据目前社区似乎有两个： https://raw.githubusercontent.com/gmt-china/china-geospatial-data/master/CN_faults.gmt 和https://gmt-china.org/data/CN-faults.dat

第一个在 https://github.com/gmt-china/china-geospatial-data 仓库中，是计划构建的中国地学数据集的一部分。第二个是位于社区主页仓库的原始数据。

**Comment by wangliang1989** [comment]
> > 断层数据目前社区似乎有两个： https://raw.githubusercontent.com/gmt-china/china-geospatial-data/master/CN_faults.gmt 和https://gmt-china.org/data/CN-faults.dat
> 
> 第一个在 https://github.com/gmt-china/china-geospatial-data 仓库中，是计划构建的中国地学数据集的一部分。第二个是位于社区主页仓库的原始数据。

**Comment by wangliang1989** [comment]
我刚刚点错了。
如果手册的命令加一句下载数据，很简单。就这样？

**Comment by core-man** [comment]
> 如果手册的命令加一句下载数据，很简单。就这样？

或许可以参考：https://docs.gmt-china.org/latest/examples/ex002/ 中射线路径的下载方式。

**Comment by wangliang1989** [comment]
那不就数据冗余了吗

> > 如果手册的命令加一句下载数据，很简单。就这样？
> 
> Yes，但是最好用 ci 缓存一下，避免每次 PR 都要下载断层数据。即在下面加一行 wget 下载断层数据。
> 
> https://github.com/gmt-china/GMT_docs/blob/7567da40a23efcaa7a3f9806234b4705454faf4d/.github/workflows/cache-data.yml#L31-L36

**Comment by seisman** [comment]
> Yes，但是最好用 ci 缓存一下，避免每次 PR 都要下载断层数据。即在下面加一行 wget 下载断层数据。

Sounds good.

**Comment by wangliang1989** [comment]
> > 如果手册的命令加一句下载数据，很简单。就这样？
> 
> Yes，但是最好用 ci 缓存一下，避免每次 PR 都要下载断层数据。即在下面加一行 wget 下载断层数据。
> 
> https://github.com/gmt-china/GMT_docs/blob/7567da40a23efcaa7a3f9806234b4705454faf4d/.github/workflows/cache-data.yml#L31-L36

OK

**Comment by core-man** [comment]
@wangliang1989 Do you want to have a try? It should be easy. You could open a new PR to test.

**Comment by wangliang1989** [comment]
> @wangliang1989 Do you want to have a try? It should be easy. You could open a new PR to test.

hao

**Comment by CovMat** [comment]
https://github.com/gmt-china/china-geospatial-data/pull/4

已提交  中国地学数据：https://gmt-china.org/data/

**Comment by core-man** [comment]
关闭这个issue？我们在https://github.com/gmt-china/china-geospatial-data/issues/5#issuecomment-852725059 中进行汇总？
