### ISSUE TITLE
中文社区博客迁移至中文文档？

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#303]
当前[中文社区博客内容](https://gmt-china.org/#posts)有待更好整理、排版、更新、删除和维护。有的博客貌似本身就是图库。我们要迁移到中文文档里进行维护吗？这样中文社区网站就比较简洁了 @seisman @wangliang1989 @CovMat

**Comment by wangliang1989** [comment]
有些不合适，比如吃饭的博客

**Comment by core-man** [comment]
> 有些不合适，比如吃饭的博客

哪些可以留在中文社区网站中，我们把GMT直接相关移动过来。社区网站我理解为GMT-China的门户网站，只要列举非技术细节的内容即可。

**Comment by wangliang1989** [comment]
有些不是news，比如稿约

**Comment by core-man** [comment]
> 有些不是news，比如稿约

那也可以放在news或其他名字。这个issue主要是讨论把技术性的博客挪过来维护。

**Comment by seisman** [comment]
有些内容放在博客里的原因就是因为中文手册里没有合适的章节可供放置。

**Comment by core-man** [comment]
上面就是初步的列表啊

**Comment by wangliang1989** [comment]
一个问题是，有些内容你看标题他确实很适合移到手册，比如GMT版本那一篇。但是你把这一篇打开来看的话，你就会发现他写的时候有当时的一个时效性。久了以后呢，他的实效性其实记录了社区的一个发展的历史，等几十年后回头看，有一定意义。

另一个问题是，如何把握相关性的阈值。比如Unix工具那一篇，距离手册相对上有一点远。

**Comment by core-man** [comment]
这个对话记录和更新有关博客的迁移紧张：

- [x] [GMT自带中国国界问题](https://gmt-china.org/blog/china-border-issues/)
  - [x] 迁移： #343 by @CovMat
  - [x] 重定向：https://github.com/gmt-china/gmt-china.org/pull/192 by @core-man

**Comment by core-man** [comment]
> 一个问题是，有些内容你看标题他确实很适合移到手册，比如GMT版本那一篇。但是你把这一篇打开来看的话，你就会发现他写的时候有当时的一个时效性。久了以后呢，他的实效性其实记录了社区的一个发展的历史，等几十年后回头看，有一定意义。

原始博文不会删除，我们只是迁移我们认为值得一直维护和更新的博文，一般是很多读者确实需要了解的，这些内容不维护是有点可惜的。中文社区的博文确实会一直记录社区的发展历史，有意义。

> 另一个问题是，如何把握相关性的阈值。比如Unix工具那一篇，距离手册相对上有一点远。

迁移工作应该需要很久，一般流程是某个维护者有一天觉得一个博文应该迁移，然后提出，大家认为可以迁移才会付诸实施。对于值不值得迁移，我们可以讨论并最后投票决定。Unix工具那一篇我也觉得有点远，所以即使要迁移也是很低的优先级。

不过说unix那个博文倒是提醒我了，鉴于国内windows用户如此多，我们是否需要在手册里开一个章节汇总windows下的各方面事宜。如果值得，我们可以单开一个issue讨论此事。

**Comment by wangliang1989** [comment]
> > 一个问题是，有些内容你看标题他确实很适合移到手册，比如GMT版本那一篇。但是你把这一篇打开来看的话，你就会发现他写的时候有当时的一个时效性。久了以后呢，他的实效性其实记录了社区的一个发展的历史，等几十年后回头看，有一定意义。
> 
> 原始博文不会删除，我们只是迁移我们认为值得一直维护和更新的博文，一般是很多读者确实需要了解的，这些内容不维护是有点可惜的。中文社区的博文确实会一直记录社区的发展历史，有意义。
> 
> > 另一个问题是，如何把握相关性的阈值。比如Unix工具那一篇，距离手册相对上有一点远。
> 
> 迁移工作应该需要很久，一般流程是某个维护者有一天觉得一个博文应该迁移，然后提出，大家认为可以迁移才会付诸实施。对于值不值得迁移，我们可以讨论并最后投票决定。Unix工具那一篇我也觉得有点远，所以即使要迁移也是很低的优先级。
> 
> 不过说unix那个博文倒是提醒我了，鉴于国内windows用户如此多，我们是否需要在手册里开一个章节汇总windows下的各方面事宜。如果值得，我们可以单开一个issue讨论此事。

你不是要迁移，你是要吸收
我们应该劝说windows用户尽快转用Linux

**Comment by core-man** [comment]
> [2017版1:100万全国标准基础地理数据](https://gmt-china.org/blog/national-geographic-database/)

是否可以将此博客更新维护至[中国地理空间数据集](https://docs.gmt-china.org/latest/dataset-CN/)。此数据应该很大，我们可以不放入数据集仓库，但是可以维护构建和使用流程。

Ping @liuzhumei @CovMat @seisman @wangliang1989 for comments.

> [GDAL/OGR: 地理空间数据格式转换神器](https://gmt-china.org/blog/gdal-ogr/)

此博客是否适合移入[用ogr2ogr实现数据转换](https://docs.gmt-china.org/latest/table/ogr2ogr/)？ Ping @seisman for comments.

**Comment by wangliang1989** [comment]
> > [2017版1:100万全国标准基础地理数据](https://gmt-china.org/blog/national-geographic-database/)
> 
> 
> 
> 是否可以将此博客更新维护至[中国地理空间数据集](https://docs.gmt-china.org/latest/dataset-CN/)。此数据应该很大，我们可以不放入数据集仓库，但是可以维护构建和使用流程。
> 
> 
> 
> Ping @liuzhumei @CovMat @seisman @wangliang1989 for comments.
> 
> 
> 
> > [GDAL/OGR: 地理空间数据格式转换神器](https://gmt-china.org/blog/gdal-ogr/)
> 
> 
> 
> 此博客是否适合移入[用ogr2ogr实现数据转换](https://docs.gmt-china.org/latest/table/ogr2ogr/)？ 
> 
> 
> 
> Ping @liuzhumei @CovMat @seisman @wangliang1989 for comments.

我觉得可以

**Comment by core-man** [comment]
> [GMT5在Windows下提示无法创建用户目录的解决办法](https://gmt-china.org/blog/user-directory-warning/)

@zhaozhiyuan1989 该问题是否只存在于  GMT 5 的 Windows 中？ GMT 6 不存在此问题的话，该博客就不迁移了。

也请 @CovMat 评论一下，因为你也是 Windows 用户。

> [Windows 下可用的 Unix 工具](https://gmt-china.org/blog/unix-tools-for-windows/)

该博客是否有必要迁移至 [Windows 下安装 GMT](https://docs.gmt-china.org/latest/install/windows/#id1) 的小节下维护？ 我个人觉得这个长度可以放入中文手册，Ping @seisman @CovMat @SeisPider for comments.

> [利用 Google Maps 获取超高精度高程数据](https://gmt-china.org/blog/google-maps-elevation-api/)

目前 GMT 的地形起伏数据最高精度是为 1 弧秒（约 30米），而 Google Maps Elevation API 提供了米级精度。

#476 中计划增加“如何提取和绘制剖面”的进阶教程，里面包含了地形起伏剖面教程；同时，Google Maps Elevation API 提供的米级精度地形起伏数据也可以放于[自定义数据](https://docs.gmt-china.org/latest/dataset/#id3)中。我觉得可以放入进阶教程和自定义数据中，Ping @seisman @SeisPider for comments.

**Comment by CovMat** [comment]
`GMT5在Windows下提示无法创建用户目录的解决办法`

现在应该不存在这个问题

**Comment by core-man** [comment]
> `GMT5在Windows下提示无法创建用户目录的解决办法`
> 
> 现在应该不存在这个问题

good

> `Windows 下可用的 Unix 工具`
> 
> 这个在安装说明里已经有了


安装说明直接给了博客的链接，而博客本身内容较短，可以直接迁移至手册？如果这个工具包比较常用的话。

**Comment by core-man** [comment]
FYI. 我根据以上讨论，提交了四个单独的 issues，请查看 https://github.com/gmt-china/GMT_docs/issues/303#issuecomment-856720606.

**Comment by core-man** [comment]
@CovMat 在 #509 中添加 VS Code 至 Windows 的可选软件中，并给出了中文社区博客[GMT脚本执行利器——VS Code](https://gmt-china.org/blog/vscode-usage/)作为安装配置教程。因此，我们是否将此博客转移至中文手册呢？其实 VS Code的安装和推荐在[地震“学”科研入门教程：编辑器](https://seismo-learn.org/seismology101/computer/editor/#vs-code)也简要提到，但是安装和配置没有深入讲解。

**Comment by seisman** [comment]
不确定要放哪里

**Comment by core-man** [comment]
> 不确定要放哪里

放附录里如何？放正文太长了。

根据GMT群里的问题，VS Code 这篇博文具有一定的价值，值得放入手册。

**Comment by core-man** [comment]
[GMT中文社区QQ群入群须知](https://gmt-china.org/blog/community-guide/) 放入 [学习资源](https://docs.gmt-china.org/latest/intro/resources/)或者附录里？然后在 https://gmt-china.org/#contact 加上链接。

**Comment by wangliang1989** [comment]
> https://gmt-china.org/#contact

https://docs.gmt-china.org/6.2/intro/resources/

写了已经

**Comment by core-man** [comment]
> > https://gmt-china.org/#contact
> 
> https://docs.gmt-china.org/6.2/intro/resources/
> 
> 写了已经

我的意思是是把入群须知的博文迁移过来，不是只写qq号。

**Comment by wangliang1989** [comment]
> > > https://gmt-china.org/#contact
> > 
> > 
> > https://docs.gmt-china.org/6.2/intro/resources/
> > 写了已经
> 
> 我的意思是是把入群须知的博文迁移过来，不是只写qq号。

我觉得无关紧要

**Comment by core-man** [comment]
closed? 因为所有计划迁移是博客都单独提交了 issue，剩余博客都与手册没有关系。
