### ISSUE TITLE
绘图实例：绘制地球内部主要界面

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#310]
Originally posted in https://github.com/gmt-china/GMT_docs/pull/293#discussion_r637982491

> 这个脚本已经过时，需要按照最新语法重写。

Refer to [How to draw a specific arc in polar coordinate system](https://forum.generic-mapping-tools.org/t/how-to-draw-a-specific-arc-in-polar-coordinate-system/1719) & [GMT Iusses #5260: Add plot -Ar|t to draw lines following theta or r direction in polar projections](https://github.com/GenericMappingTools/gmt/issues/5260)

In case that we forget it.

**Comment by seisman** [comment]
The **-JP** syntax has changed in GMT 6.1 (although old syntax is still supported). See https://docs.generic-mapping-tools.org/6.1/cookbook/coordinate-transformations.html#linear-projection-with-polar-coordinates-jp-jp for the new syntax for **-JP**.

For this example, we need to update the old syntax `-JPa10c/15` to the new syntax, and some subsequent changes may be needed. However, I don't have GMT 6.1.1 installed, so contributions are welcomed.
