### ISSUE TITLE
Bump to GMT 6.2.0

### ISSUE THREAD

**Issue by seisman** [gmt-china/GMT_docs#313]
Currently, the repository uses GMT 6.1.1 to run the scripts and produce the images. 

GMT 6.2.0rc2 was released on May 24, 2021, and I believe the official GMT 6.2.0 will be released in the next few days or weeks.

What we're going to do:

- [x] Finish issues that are necessary before bumping the GMT version
- [x] Quickly go through the HTML documentation and see if there are any obvious errors like the CN faults ones mentioned in #301 
- [x] Quickly go through the PDF documentation and see if there are any obvious errors
- [x] Making the 6.1.1 release for the documentation
- [x] Bump to GMT 6.2.0 in the CI workflow and the documentation (#314)

**Comment by core-man** [comment]
Issues that are necessary before bumping the GMT version:

- [ ] #328 
- [ ] #323 
- [ ] #310

**Comment by core-man** [comment]
Shall we submit some PRs into the `6.2-dev` branch so that the update is smooth?

**Comment by seisman** [comment]
No, we will submit directly to the master branch.

**Comment by core-man** [comment]
> No, we will submit directly to the master branch.
In this way, the documentation may have both 6.1 and 6.2 at the same, right? We won't make all changes in one PR, no?

**Comment by seisman** [comment]
> In this way, the documentation may have both 6.1 and 6.2 at the same, right? We won't make all changes in one PR, no?

Yes, but the migration can be done in a few simple PRs, so it won't cause any troubles.

**Comment by seisman** [comment]
Please let me know if you want to work on the migration. Or I can do it myself.

**Comment by core-man** [comment]
> Please let me know if you want to work on the migration. Or I can do it myself.

Sure, I'll have a try.
