### ISSUE TITLE
Add a note for the transparency issue caused by Ghostscript default setting

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#323]
We cannot plot transparency using Ghostscript >= 9.50. This is caused by the default `-dSAFER` option in Ghostscript .

See the `-dSAFER` option in Ghostscript (https://www.ghostscript.com/doc/current/Use.htm)

> Ghostscript now (as of 9.50) defaults to SAFER being active.

In order to plot transparency, we have to methods:
- Use Ghostscript < 9.50 (Not Recommended)
- Set `-dNOSAFER` to Ghostscript (Recommended)

For the second method, we just need to add `-dNOSAFER`  to the **C** option (Not **-C** parameter) of [begin](https://docs.gmt-china.org/latest/module/begin/):
> gmt begin [ prefix ] [ formats ] [ options ] [ -C ] [ -V[level] ]
> options:
> Cargs: 额外传递给Ghostscript的选项

```
gmt begin fig1 pdf C-dNOSAFER
```

See an example:
```Bash
gmt begin tran pdf C-dNOSAFER
gmt basemap -JH14c -Rg -Bpx60
gmt coast -W1/0.2p -N1

# 绘制第一个不透明矩形框
gmt plot -W1p -L -Gred <<EOF
100 -20
100 20
140 20
140 -20
EOF

# 绘制第二个透明矩形框
gmt plot -W1p -L -Gred -t60 <<EOF
280 -20
280 20
320 20
320 -20
EOF

gmt end show
```

![trans](https://user-images.githubusercontent.com/50591376/119784629-fbc79b80-bf00-11eb-962c-34e84faca93f.png)

We may add a note in [color tutorial](https://docs.gmt-china.org/latest/basis/color/#id4).

**Comment by seisman** [comment]
> We cannot plot transparency using Ghostscript >= 9.50.

I believe it works for gs >= 9.53 with latest GMT versions.

**Comment by core-man** [comment]
gmt 6.1?

**Comment by seisman** [comment]
I believe GMT 6.1.1 works with gs 9.53 or 9.54.

**Comment by core-man** [comment]
GMT=6.1 and gs=9.50 is okay. So I close this issue~
