### ISSUE TITLE
Add an issue template

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#324]
- https://github.com/seismo-learn/software/tree/main/.github/ISSUE_TEMPLATE
- https://github.com/GenericMappingTools/pygmt/tree/master/.github/ISSUE_TEMPLATE

**Comment by seisman** [comment]
考虑到这是一个文档，而不是一个软件，我感觉没有必要准备一个 issue 模板，也很难像 pygmt 或者 seismo-learn/software 那样找到一个通用模板可以覆盖大多数 issue
