### ISSUE TITLE
关于中国地质图数据

### ISSUE THREAD

**Issue by CovMat** [gmt-china/GMT_docs#326]
因为从数据集中移除了，因此不能再放在中国地学数据集这个章节下。

那么作为例子移动到绘图实例下是否合适？

**Comment by CovMat** [comment]
> 是否放在数据集中还需要再考虑。

因为地质图有很多小区域的结构，数据体积应该是无法缩小了，20多M应该没办法避免

**Comment by CovMat** [comment]
还是说换成一个7z高压缩包？

**Comment by core-man** [comment]
关于数据集：先数据仓库提交issue，详细描述一下此数据集

关于文档：建议删除相关内容先，带数据集问题解决后再决定是否增加到文档

**Comment by core-man** [comment]
Close this issue, since we may want to discuss it in https://github.com/gmt-china/china-geospatial-data/issues/3?
