### ISSUE TITLE
One failing subplot example 

### ISSUE THREAD

**Issue by seisman** [gmt-china/GMT_docs#328]
https://docs.gmt-china.org/latest/tutorial/subplot/

The last example produces the following image: 

![image](https://user-images.githubusercontent.com/3974108/119919549-adce8a00-bf38-11eb-90cb-c10a836e3667.png)

but the expected output is:

![image](https://user-images.githubusercontent.com/3974108/119919600-c343b400-bf38-11eb-98a2-cb61e6432e18.png)

I can get the expected output with GMT 6.2.0 but it seems it doesn't work with GMT 6.1.1.

**Comment by wangliang1989** [comment]
我用的6.1.1，报错是basemap [ERROR]: Must specify at least one of -A, -B, -D, -L, -T。

**Comment by core-man** [comment]
See another bug. I use `-Y-h-2c` and the figure cannot be plotted correctly.
```bash
gmt begin complex-subplot pdf
gmt subplot begin 1x1 -Ff15c/3c -A -BWSen
gmt subplot set 0 -A'(a)'                                                
gmt basemap -R0/10/0/10 -JX?                                             
gmt subplot end                                                              
                                                                               
gmt subplot begin 1x1 -Ff15c/3c -A -BWSen -Y-h-2c                             
gmt subplot set 0 -A'(b)'                                                
gmt basemap -R0/10/0/10 -JX? -B1
gmt subplot end                                                              
gmt end show             
```
![complex-subplot](https://user-images.githubusercontent.com/50591376/120156794-ea460280-c224-11eb-8db6-13896e25d1c9.png)

**Comment by seisman** [comment]
> See another bug using GMT6.1.1. I use `-Y-h-2c` and the figure cannot be plotted correctly.

This is not a bug. Similar to classic mode, when shifting the origin to left or bottom side, the plot will be outside of the paper.

**Comment by seisman** [comment]
If you still have GMT 6.1.1 installed, could you please provide a working example?

**Comment by core-man** [comment]
> If you still have GMT 6.1.1 installed, could you please provide a working example?

okay
