### ISSUE TITLE
中文支持: 指南针东西南北

### ISSUE THREAD

**Issue by seisman** [gmt-china/GMT_docs#330]
https://docs.gmt-china.org/latest/chinese/showcase/

这一节展示了GMT的中文支持以及月份和星期的汉化。理论上在绘制指南针时，默认的 NSWE 也是可以汉化为东西南北的。有兴趣的可以试试。

**Comment by ZMAlt** [comment]
> 理论上在绘制指南针时，默认的 NSWE 也是可以汉化为东西南北的

这里的指南针汉化指的是和[月份以及星期类似的汉化](https://docs.gmt-china.org/latest/chinese/showcase/#id2)吗？  
我试了下，是不行的。

类似[中文标签和中文标题](https://docs.gmt-china.org/latest/chinese/showcase/#id1)的做法是可以的。

**Comment by seisman** [comment]
在 GMT 的 share/localization 目录下，有中文配置文件 `gmt_cn1.locale`。应该需要把里面的 WESN 改成“东西南北”才可以

**Comment by ZMAlt** [comment]
好的，我已经看到了。等有空测试下

**Comment by core-man** [comment]
能否具体说明增加啥内容？增加到那个页面？

**Comment by ZMAlt** [comment]
@core-man  应该是在 `gmt_cn1.locale` 中修改 `WESN` 为中文的 `东西南北` ，然后通过设置`GMT_LANGUAGE`，自动实现指南针的汉化。然后在 https://docs.gmt-china.org/latest/chinese/showcase/ 加一小节。

---
@seisman 我没有实现预想的效果。

我对[中文月份](https://docs.gmt-china.org/6.2/chinese/showcase/#id2)部分的设置也有些疑问，不知道我理解的对不对。
```bash
# 进入 GMT 语言定义文件所在目录
cd `gmt --show-sharedir`/localization
# 备份中文语言文件
cp gmt_cn1.locale gmt_cn1.locale_old
# 将中文编码方式从默认的 GB2312 修改为 UTF8 编码，这样才能正常显示中文月份
iconv -f GBK -t UTF8 gmt_cn1.locale
```
1. `gmt_cn1.locale`文件的编码是 GB2312？ 执行最后一句确实能在终端看到中文。但是我用`file`和 vim 查看编码都不是 GBK ?
2. 我分别试了 GBK 和 GB2312 ，执行最后一条语句，都能在终端看到中文。GBK 和 GB2312 应该是两种编码？
3. `iconv -f GBK -t UTF8 gmt_cn1.locale` 语句转换后的结果输出到终端，并没有重定向，所以`gmt_cn1.locale`的编码其实没有变。
4. 即便是将 `gmt_cn1.locale` 的编码确实变为 UTF8，我还是没实现中文月份和中文星期，指南针当然也没。不知道哪里的问题。

---

系统 Mac  gmt 6.2

**Comment by ZMAlt** [comment]
> 1. `gmt_cn1.locale`文件的编码是 GB2312？ 执行最后一句确实能在终端看到中文。但是我用`file`和 vim 查看编码都不是 GBK ?

很奇怪，file 命令和 vim 下的 set fileencoding 显示的编码分别为 ISO-8859 和 latin1 ， 都不是 GKB，但是用 iconv -f GKB 确实能成功。如果再 gmt 官方修改方向的中文的话，在网页操作会自动转换为 UTF-8，在终端还没试过怎么弄？或许先转为 utf8，修改，然后再转换为 GBK，然后提交？或者直接提交 utf-8？不知道 windows 这边的中文要不要转编码，我现在没有 win机器了

**Comment by seisman** [comment]
> 很奇怪，file 命令和 vim 下的 set fileencoding 显示的编码分别为 ISO-8859 和 latin1 ，latin1 是 ISO-8859-1 的别名。不是 GBK，但是用 iconv -f GBK 确实能成功。

使用 `enca -L zh_CN gmt_cn1.locale` 得到的是 GB2312.

> 如果在 gmt 官方修改方向的中文的话，在网页操作会自动转换为 UTF-8，在终端还没试过怎么弄？或许先转为 utf8，修改，然后再转换为 GBK，然后提交？

个人感觉用 vscode 修改是最方便的。

> 或者直接提交 utf-8？不知道 windows 这边的中文要不要转编码，我现在没有 win机器了

Windows 下需要 GB2312，Linux/macOS 需要 UTF8。二者必然有一个要做一下转换。

**Comment by ZMAlt** [comment]
https://github.com/GenericMappingTools/gmt/pull/7068/files

我用 vscode 修改编码为 GB2312 后修改的。但是看上去有点奇怪

<img width="583" alt="image" src="https://user-images.githubusercontent.com/35285040/198871918-08aa97a5-eafd-4f10-86b5-d024101241cc.png">

**Comment by seisman** [comment]
应该是 github PR 显示的问题。直接看 https://github.com/ZMAlt/gmt/blob/Chinese_compass/share/localization/gmt_cn1.locale 是没问题的。

28-29行：

> # The following lines give the translation of the 4 major compass directions (WESN).
> # Name in full (optionally capitalized), abbreviation of longitude and latitude on map edge and wind direction (may be more than one letter).

建议直接将英文翻译成中文，而不是写成：

> # 下面给出玫瑰图四个方向的中文名称
> # 由于玫瑰图仅使用缩写，因此只修改最后一行即可

**Comment by ZMAlt** [comment]
完了，改不了了，再打开都变成了 锟斤拷，无论怎么换编码都回不去了
