### ISSUE TITLE
审稿流程

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#341]
因为现在活跃人数达4人之下，我们是否明确一下审稿流程，以免只有一人审稿即被merge了。设置call review 和 final review call?抑或至少两个reviewer

**Comment by seisman** [comment]
"final review call" sounds good to me.

**Comment by core-man** [comment]
@gmt-china/contributors 建立了一个新的标签`final review call`，当某个reviewer觉得一个pr已经满意后，可以贴上这个标签，等半天，一天或者两天，要是没其他reviewer有额外意见，就可以直接merge了。

**Comment by wangliang1989** [comment]
这和approve后等几天有什么区别呢

**Comment by core-man** [comment]
本质上没区别，但是算是正式的通知吧。如果其他reviewer看到这个标签后，依然没有审稿，就默认同意了。

**Comment by wangliang1989** [comment]
可能田冬冬来点merge要稳妥些。你看我只敢点approve，一般不点merge

**Comment by core-man** [comment]
> 可能田冬冬来点merge要稳妥些。你看我只敢点approve，一般不点merge

这也是 final review call 的目的，一个项目不能一直只有一个 maintainer，还要多培养几个。普通的PR，两个 maitnainer 达成一致就够了。

**Comment by wangliang1989** [comment]
你现在的机制其实是1个人决定+等一段时间，为什么不是两个人同意？似乎两个人同意好些

**Comment by core-man** [comment]
有的 PR 比较简单，如果一天没有第二个人 review，其实也可直接 merge 了。

**Comment by seisman** [comment]
> 这和approve后等几天有什么区别呢

我目前在管理 N 多个repository（gmt, PyGMT, seismo-learn 的好几个，gmt-china 的好几个，以及SAC_Docs），所以我并不一定会有时间及时 review 各个 PR。

"final review call" 意味着这个 PR 默认在一天后就会 merge，我看到后会给这个 PR 更高的优先级。对于其他维护者而言，也是一样的。

**Comment by core-man** [comment]
我目前也在管理 N 多个repository（seismo-learn 和 MIG 的好几个），也给 gmt-china， SAC_Docs，以及 pygmt 贡献和 review。所以要么一个 pr 是我的最高优先级，要么被要点名及时 review，抑或 final review call，否则我可能也会不能及时review每个pr。

**Comment by seisman** [comment]
Agreed.
