### ISSUE TITLE
更新中国地学数据集概述

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#345]
v0.1.0 版本已经发布：https://github.com/gmt-china/china-geospatial-data/issues/20

我们可以完善[中国地学数据集概述](https://docs.gmt-china.org/latest/dataset-CN/overview/)。例如，如何使用数据集；如何下载。

**Comment by core-man** [comment]
@CovMat 因为目前主要是你在建设数据库，所以把这个 issue 分配给你？

**Comment by CovMat** [comment]
好

**Comment by core-man** [comment]
https://gmt-china.org/data/ 顺便也更新一下吧

**Comment by CovMat** [comment]
> https://gmt-china.org/data/ 顺便也更新一下吧。我觉得加上中文手册和数据仓库的链接以及一个剪短note在最开头即可。

网站部分你来搞

**Comment by core-man** [comment]
> > https://gmt-china.org/data/ 顺便也更新一下吧。我觉得加上中文手册和数据仓库的链接以及一个剪短note在最开头即可。
> 
> 网站部分你来搞

okay

**Comment by seisman** [comment]
感觉这一章还需要进一步完善。目前只提到了这两套数据，并没有提到 CN-border-La, CN-border-L1 这些具体的数据以及它们的内容是什么。这些信息在 https://github.com/gmt-china/china-geospatial-data/ 的 README 里有提到，但是这个文件通常用户都是不读的。所以还是需要在手册里介绍。

**Comment by core-man** [comment]
这个 issue 在 #358 接受后可以关了吗？
