### ISSUE TITLE
配置 CI 服务器中的 GMT 使得其支持中文

### ISSUE THREAD

**Issue by seisman** [gmt-china/GMT_docs#348]
GMT 中文社区的部分脚本包含了中文，由于目前 CI server 并没有配置中文，所以脚本绘图中文会显示乱码。

有可能可以配置 CI 服务器使得其支持中文。中文字体可以考虑用 文泉驿、Noto Sans CJK 等开源字体。

**Comment by ZMAlt** [comment]
虽然 #375 测试成功了，但还是有问题。
https://docs.gmt-china.org/latest/chinese/unix/#id1
