### ISSUE TITLE
发布 v6.1 手册

### ISSUE THREAD

**Issue by seisman** [gmt-china/GMT_docs#351]
GMT 6.2.0 已经发布。我们将于近期发布中文手册的 v6.1 版本，并开始着手将手册升级及 GMT 6.2.0。

请列出你觉得有必要在发布 v6.1 版本之前解决的 issue 和 PR。

**Comment by core-man** [comment]
## Issues

- [ ] #345
- [ ] #336 
- [ ] #328
- [ ] #314
- [ ] #313
- [ ] #253
- [ ] #234

## PRs

- [ ] #349
- [ ] #350

**Comment by seisman** [comment]
I believe most issues are not critical and don't have to be fixed in the 6.1 release.

**Comment by core-man** [comment]
> I believe most issues are not critical and don't have to be fixed in the 6.1 release.

Agreed except that #253. Please wait for one week for me to finish it.

**Comment by seisman** [comment]
OK. Plan to make the release this Sunday.

**Comment by core-man** [comment]
See https://github.com/gmt-china/GMT_docs/issues/313#issue-901165539:

> - Quickly go through the HTML documentation and see if there are any obvious errors like the CN faults ones mentioned in #301
> - Quickly go through the PDF documentation and see if there are any obvious errors

我们计划本周日发布6.1手册，大家有空可以浏览 HTML 和 PDF 手册，看看是否有明显错误可以快速修正 @gmt-china/contributors

**Comment by core-man** [comment]
@seisman Please release it Sunday night so that I can review HTML and PDF tomorrow.

**Comment by seisman** [comment]
@core-man Or do you want to make the release?

**Comment by core-man** [comment]
> @core-man Or do you want to make the v6.1 release?

I think it just needs a release operation, right?

**Comment by seisman** [comment]
Yes.

Old releases have names like 6.0.0, 5.4.5, but perhaps we should use `v6.1` this time, rather than `6.1.0`, `v6.1.0` or `6.1`.

**Comment by core-man** [comment]
Okay, I'll do it tomorrow 9pm.

**Comment by core-man** [comment]
I am releasing v6.1.

**Comment by seisman** [comment]
> I am releasing v6.1.

Sounds good.

**Comment by core-man** [comment]
Done~ See https://github.com/gmt-china/GMT_docs/releases.
