### ISSUE TITLE
“中国区域地理信息数据集”模板

### ISSUE THREAD

**Issue by seisman** [gmt-china/GMT_docs#353]
目前已经有了 CN-faults 和 CN-border 两套数据，以及正在添加的 CN-block 数据。

在介绍这些数据时，最好有一套统一的模板，以方便维护和更新。例如，应提供如下信息：

1. 简介：一两句话
2. 这套数据里包含哪些文件？每个文件是什么内容？比如 CN-border 里包含了三个数据文件
3. 获取方式以及使用方法：可以直接链接到 https://docs.gmt-china.org/latest/dataset-CN/overview/, 或者写一个简单啊的使用说明，保存到一个小文件里，在介绍每个数据时都把这个文件包含进去
4. 绘图展示
5. 数据来源：原始文献？谁做的数字化？

**Comment by seisman** [comment]
Ping @CovMat

**Comment by CovMat** [comment]
好的。现在这5点，除了第二点没写，其他都有写。我之后再加一个PR，把三个数据的第2点都补充上

**Comment by core-man** [comment]
> 目前已经有了 CN-faults 和 CN-border 两套数据，以及正在添加的 CN-block 数据。
> 
> 在介绍这些数据时，最好有一套统一的模板，以方便维护和更新。例如，应提供如下信息：
> 
> 1. 简介：一两句话
> 2. 这套数据里包含哪些文件？每个文件是什么内容？比如 CN-border 里包含了三个数据文件
> 3. 获取方式以及使用方法：可以直接链接到 [https://docs.gmt-china.org/latest/dataset-CN/overview/, 或者写一个简单啊的使用说明，保存到一个小文件里，在介绍每个数据时都把这个文件包含进去](https://docs.gmt-china.org/latest/dataset-CN/overview/%EF%BC%8C%E6%88%96%E8%80%85%E5%86%99%E4%B8%80%E4%B8%AA%E7%AE%80%E5%8D%95%E5%95%8A%E7%9A%84%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E%EF%BC%8C%E4%BF%9D%E5%AD%98%E5%88%B0%E4%B8%80%E4%B8%AA%E5%B0%8F%E6%96%87%E4%BB%B6%E9%87%8C%EF%BC%8C%E5%9C%A8%E4%BB%8B%E7%BB%8D%E6%AF%8F%E4%B8%AA%E6%95%B0%E6%8D%AE%E6%97%B6%E9%83%BD%E6%8A%8A%E8%BF%99%E4%B8%AA%E6%96%87%E4%BB%B6%E5%8C%85%E5%90%AB%E8%BF%9B%E5%8E%BB)
> 4. 绘图展示
> 5. 数据来源：原始文献？谁做的数字化？

**Comment by core-man** [comment]
see https://github.com/gmt-china/GMT_docs/pull/364#discussion_r651781794

> 我们需要从原始数据出发，解释如何从原始数据得到 GMT 可用的数据。
