### ISSUE TITLE
修改GMT数据概述？

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#362]
我们是否可以像 [中国地理空间数据集](https://docs.gmt-china.org/latest/dataset-CN/) 那样在 index 简要介绍GMT数据。即把 [GMT数据概述](https://docs.gmt-china.org/latest/dataset/overview/#) 中每小节总结的话移动 index 中。概述只包括技术细节，要不然每类数据总结隐藏的太深。我现在看index，其实不知道每种数据到底是啥类型。

> GMT内置数据是指在安装GMT时就已经安装了的数据，因而可以直接使用。这类数据包括
> - GSHHG: 全球高分辨率海岸线数据
> - DCW: 世界数字图表

> GMT远程数据保存在GMT数据服务器上。当需要使用某个数据时，GMT会自动将数据下载到本地。目前，GMT提供了如下远程数据：
> - earth_relief: 全球地形起伏数据
> - earth_day 和 earth_night: 地球昼夜卫星影像
> - earth_age: 地球洋壳年龄数据
> - earth_mask: 地球掩膜数据

> 除了GMT官方提供的内置数据和远程数据外，用户还可以自行准备数据，建立GMT数据库，供GMT使用。GMT中文社区整理了一些自定义数据，用户可以选用，包括：
> - GADM: 全球行政区划数据库
> - PB2002: 全球板块边界数据
> - 中国地理空间数据集

**Comment by seisman** [comment]
确实有点乱，主要是数据的使用方式完全不一样。但我不确定你想怎么改。简单改下，发个PR看看？

**Comment by core-man** [comment]
> 确实有点乱，主要是数据的使用方式完全不一样。但我不确定你想怎么改。简单改下，发个PR看看？

will do it tomorrow.
