### ISSUE TITLE
模块手册增加紧凑型模块列表？

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#366]
目前只有每个模块按照类型，一行一个模块：https://docs.gmt-china.org/latest/module/
这种排行对于新手学习比较有好，但是 GMT 熟练的用户要找一个模块时候需要往下翻。
因此，我们是否在顶部建立一个紧凑型列表，参考官方手册：https://docs.generic-mapping-tools.org/latest/modules.html

**Comment by seisman** [comment]
Definitely YES!

**Comment by seisman** [comment]
FYI, I'm working on this.
