### ISSUE TITLE
更新地图投影首页？

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#368]
See https://docs.gmt-china.org/latest/proj/ and https://docs.generic-mapping-tools.org/dev/cookbook/map-projections.html.

- 中文手册将投影分为三类：笛卡尔**线性**投影、极坐标投影、地图投影
- GMT 官方手册使用 Miscellaneous projections 表示剩余地图投影，中文手册使用 Thematic
- 绘图时候将 **Other** 下包含了笛卡尔坐标的多种形式以及极坐标

感觉略微混乱，更新一下？

- [x] **笛卡尔线性投影** -->> **笛卡尔投影**
- [x] 图片中**Other**分类两列：**笛卡尔投影** 和 **极坐标投影**，与文字描述对应？
- [x] **Thematic** or **Miscellaneous**?

----

此外，我们是否增加投影汇总表格，参考 https://www.pygmt.org/latest/projections/index.html#projection-table 和 https://docs.generic-mapping-tools.org/dev/cookbook/map-projections.html 。当前只是一张图片展示分类。

**Comment by seisman** [comment]
图片来自于 https://docs.generic-mapping-tools.org/dev/cookbook/options.html#option-j

投影汇总表格见 https://docs.gmt-china.org/latest/option/J/

**Comment by core-man** [comment]
> 图片来自于 https://docs.generic-mapping-tools.org/dev/cookbook/options.html#option-j
> 
> 投影汇总表格见 https://docs.gmt-china.org/latest/option/J/

中文手册正好和官方放的位置反过来了。
