### ISSUE TITLE
增加绘制国界省界汇总小节？

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#385]
中文手册在多处提高不同的绘制国界和省界的方法和数据库：
- [入门教程：绘制国界/州界 (GSSHG)](https://docs.gmt-china.org/latest/tutorial/coastline/#id5)
- [DCW: 使用示例](https://docs.gmt-china.org/latest/dataset/dcw/#id6)
- [GADM: 全球行政区划数据库](https://docs.gmt-china.org/latest/dataset/gadm/#id4)
- [CN-border: 中国国界省界数据](https://docs.gmt-china.org/latest/dataset-CN/CN-border/)

[gmt-china.org/blog/2018-03-17-china-border-issues](https://github.com/gmt-china/gmt-china.org/edit/master/content/blog/2018-03-17-china-border-issues/index.md) 也提到此事:
> 目前已知的几套国界数据包括：
> - [GMT自带的GSHHG数据](https://docs.gmt-china.org/latest/dataset/gshhg/)：全球海岸线、国界、部分省/州界数据
> - [GMT自带的DCW数据](https://docs.gmt-china.org/latest/dataset/dcw/)：全球行政区划数据，包含洲界、国界、省界
> - [GADM数据](https://docs.gmt-china.org/latest/dataset/gadm/)
> - 社区提供的一套[相对准确的国界、省界数据](/example/ex003)

我觉得有必要将这些方式的链接汇总在一个文档种，方便用户查阅。暂时还没想好放在哪里。

**Comment by wangliang1989** [comment]
现在不就是都汇总到了那个china geospatial data那里吗

**Comment by core-man** [comment]
> 现在不就是都汇总到了那个china geospatial data那里吗

我的意思不是特指中国国界绘制，是 GMT 绘制国界的方法和数据库汇总。方便用户在一个地方查找到四个方式的链接。

**Comment by core-man** [comment]
> 外国的按照一般的画法画不就行了？只有中国的需要整理

比如 GSHHG 没有亚洲国家的省界，DCW 和 GADM 有。需要绘制亚洲省界，就需要用DCW或GDAM。

**Comment by wangliang1989** [comment]
> > 外国的按照一般的画法画不就行了？只有中国的需要整理
> 
> 比如 GSHHG 没有亚洲国家的省界，DCW 和 GADM 有。需要绘制亚洲省界，就需要用DCW或GDAM。

这个在seisman博客里有

**Comment by core-man** [comment]
> 这个在seisman博客里有

我们要尽量把seisman博客的内容迁移到各手册中维护。

**Comment by wangliang1989** [comment]
其实seisman博客里的基本都有，把那个搬过来，在那个基础上加几个应用的例子就好了，另外，好像DCW的国界现在是对的@core-man

**Comment by core-man** [comment]
> 其实seisman博客里的基本都有，把那个搬过来，在那个基础上加几个应用的例子就好了，另外，好像DCW的国界现在是对的@core-man

Good. Do you have time to help with this issue?

**Comment by wangliang1989** [comment]
> > 其实seisman博客里的基本都有，把那个搬过来，在那个基础上加几个应用的例子就好了，另外，好像DCW的国界现在是对的@core-man
> 
> Good. Do you have time to help with this issue?

没有时间，我有点时间要先处理sac手册。因为我跟着要用新sac了。你可以先去写，然后我给你的pr加几个应用例子

**Comment by core-man** [comment]
https://github.com/gmt-china/china-geospatial-data/issues/41 描述了更多中国行政区划数据和用法
