### ISSUE TITLE
-R 选项的 6 种坐标

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#386]
[六种坐标](https://docs.gmt-china.org/latest/option/R/#id2):

> 其中地理坐标、浮点坐标、绝对时间坐标和相对时间坐标在数据类型中已经介绍过，此处不再赘述。

说好不赘述，还在赘述了**地理坐标**。此小节是否可以与**数据类型**等重新写。参考 [GMT -R option](https://docs.generic-mapping-tools.org/latest/cookbook/options.html#data-domain-or-map-region-the-r-option)。

**Comment by wangliang1989** [comment]
似乎是不再赘述这句话需要删。这里写地理坐标和数据类型写地理坐标不是一个意思

**Comment by seisman** [comment]
这里其实是比较容易误解的地方。

数据类型一节介绍的是 GMT 支持读入哪些数据格式，比如 123.45, 123.45E, 2020-01-01T02:03:04。

在 -R 选项里，除了支持以上提到的数据格式之外，还支持其他格式，比如 -Rg, -Rd, -R-2pi/2pi3/0/1 等。

所以这两者其实是无法合并到一起的，但或许哪里可以改一改以避免这些误解。
