### ISSUE TITLE
gmt 部分命令存在未翻译的英文

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#390]
- [ ] [fitcircle](https://docs.gmt-china.org/latest/module/fitcircle/) 
- [ ] [gmtconnect](https://docs.gmt-china.org/latest/module/gmtconnect/)
- [ ] [gmtselect/](https://docs.gmt-china.org/latest/module/gmtselect/)
- [ ] [grd2xyz](https://docs.gmt-china.org/latest/module/grd2xyz/)
- [ ] [grdimage](https://docs.gmt-china.org/latest/module/grdimage/)
- [ ] [grdinfo](https://docs.gmt-china.org/latest/module/grdinfo/)
- [ ] [mapproject/](https://docs.gmt-china.org/latest/module/mapproject/)
- [ ] [psconvert](https://docs.gmt-china.org/latest/module/psconvert/)
- [ ] [rose](https://docs.gmt-china.org/latest/module/rose/)
- [ ] [sample1d](https://docs.gmt-china.org/latest/module/sample1d/)
- [ ] [text](https://docs.gmt-china.org/latest/module/text/)

**Comment by core-man** [comment]
这个 issue 太靠后，而且没有详细描述具体要求。可以把每个模块未翻译的部分单独提简单的 issue 让大家帮忙解决？

**Comment by seisman** [comment]
这些英文存在的原因并不是因为忘了翻译或怎样，而是因为最初在整理的时候无法理解英文说明的含义及其意义。翻译本身并不难，难的是如何更准确地解释清楚。

另外，很多模块都需要比对中文手册做更改，所以我觉得这个issue可以关闭。

**Comment by core-man** [comment]
不先解决这些小的未翻译点吗？

**Comment by seisman** [comment]
只是单纯的翻译没什么意义，翻译成中文之后依然看不懂到底在说什么。所以每一个点都需要额外的精力以及测试去理解其含义并进一步解释，工作量大且并不重要。

**Comment by core-man** [comment]
> 只是单纯的翻译没什么意义，翻译成中文之后依然看不懂到底在说什么。所以每一个点都需要额外的精力以及测试去理解其含义并进一步解释，工作量大且并不重要。

那我们在 #602 里一点一点改吧？

**Comment by seisman** [comment]
没必要单独提 issue 去改，理论上所有的模块都需要重新审核一遍，因为有些可能是自 6.0 之后就没有再更新过，介绍的依然是老语法。

**Comment by core-man** [comment]
> 没必要单独提 issue 去改，理论上所有的模块都需要重新审核一遍，因为有些可能是自 6.0 之后就没有再更新过，介绍的依然是老语法。

我也是这么想说，但是如何有效地开展这个审核工作？

我在 #602 中想先修改每个模块的“语法”。然后，再根据修改过程中积累的结果，去重新审核不一致的地方，逐一解决。这个过程中自然要逐一提交 issue, no?

**Comment by core-man** [comment]
对于标准选项我是这么想说，因为一般较短，所以可以针对每个选项提一个重新审核的 issue，如 #595. 然后整体进展记录在 #492 中。

同一类配置参数也可以这么来。

**Comment by seisman** [comment]
> 我在 #602 中想先修改每个模块的“语法”。然后，再根据修改过程中积累的结果，去重新审核不一致的地方，逐一解决。这个过程中自然要逐一提交 issue, no?
> 
> 还是你想一个pr解决一个模块的所有审核工作？

我建议一个 PR 解决一个模块。原因在于，每个模块之间近似是独立的，而每个模块的语法介绍、各个选项之间是耦合在一起的。一个模块一个PR的好处在于，可以更宏观地看待整个模块的文档，进一步了解多个选项组合在一起有什么功能，每个模块应该增加哪些示例等等。

**Comment by seisman** [comment]
> 对于标准选项我是这么想说，因为一般较短，所以可以针对每个选项提一个重新审核的 issue，如 #595. 然后整体进展记录在 #492 中。
> 
> 同一类配置参数也可以这么来。

我之前的做法是 `tree -aI .git > TODO.txt` 生成一个所有文件的列表，然后审核完一个文件就从列表中删一个文件。

**Comment by core-man** [comment]
> 我建议一个 PR 解决一个模块。原因在于，每个模块之间近似是独立的，而每个模块的语法介绍、各个选项之间是耦合在一起的。一个模块一个PR的好处在于，可以更宏观地看待整个模块的文档，进一步了解多个选项组合在一起有什么功能，每个模块应该增加哪些示例等等。

对贡献者和审稿者来说，会比较辛苦。不过，如果遇到很复杂的模块，到时候随机应变吧，可以分成几个 pr 解决，比如 plot 模块。

那我们在 #469 里列一个模块的 TODO 清单来记录吧？

> 我之前的做法是 tree -aI .git > TODO.txt 生成一个所有文件的列表，然后审核完一个文件就从列表中删一个文件。

可以。

**Comment by seisman** [comment]
> 对贡献者和审稿者来说，会比较辛苦。不过，如果遇到很复杂的模块，到时候随机应变吧，可以分成几个 pr 解决，比如 plot 模块。

可以
