### ISSUE TITLE
更新维护指南？

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#404]
当前维护指南还不够精细和全面，需要更新和补全。

参考指南：
- seismo-learn: https://seismo-learn.org/contributing/
- gmt-china: https://github.com/gmt-china/gmt-china.org/issues/155
- pygmt 贡献和维护指南

其他注意事项：
- https://github.com/gmt-china/GMT_docs/pull/356#discussion_r651515169
- https://github.com/gmt-china/GMT_docs/pull/321#issuecomment-849286273
- https://github.com/gmt-china/GMT_docs/pull/438#issuecomment-868999366
- https://github.com/gmt-china/GMT_docs/pull/493#issuecomment-872260628

**Comment by seisman** [comment]
目前 contributing 是一章多个小节。是否要把所有内容放在单个文件里，这样显示的时候是单个页面。

**Comment by core-man** [comment]
> 目前 contributing 是一章多个小节。是否要把所有内容放在单个文件里，这样显示的时候是单个页面。

我应该会在下个月参考seismo-learn弄个完整的贡献指南，先保留现状吧。

**Comment by seisman** [comment]
我其实并不想弄一个完整的贡献指南，seismo-learn 中的已经过于复杂了。指南越长越没有读下去的欲望。

**Comment by core-man** [comment]
其实可以把第一次贡献需要读的汇总在一块。参考性质的，偶尔要查询的放一块。

seimo-learn 还牵扯到维护者指南，有些并不需要一般的贡献者阅读。

**Comment by core-man** [comment]
要不先放一块，搞成一个文档再说。

**Comment by core-man** [comment]
#645 中将所有贡献指南集中在一个文档中。未来计划放入的内容有：
- #624 
- PR 提交和审稿流程

**Comment by seisman** [comment]
> * PR 提交、审稿、修改流程

这部分内容还是放在seismo-learn里吧

**Comment by core-man** [comment]
> > * PR 提交、审稿、修改流程
> 
> 这部分内容还是放在seismo-learn里吧

Okay~
