### ISSUE TITLE
splitxyz is renamed to gmtsplit in GMT 6.2.0

### ISSUE THREAD

**Issue by seisman** [gmt-china/GMT_docs#408]
```
/home/runner/work/GMT_docs/GMT_docs/source/module/index.rst:178: WARNING: unknown document: gmt:splitxyz
/home/runner/work/GMT_docs/GMT_docs/source/module/filter1d.rst:153: WARNING: unknown document: splitxyz
```

Need to rename "splitxyz" to "gmtsplit" to fix these two warnings.

**Comment by core-man** [comment]
Shall we open an issue so that we can better organize GMT 6.2 updating?

**Comment by seisman** [comment]
It's unclear to me what you mean.

**Comment by core-man** [comment]
> It's unclear to me what you mean.

I mean GMT 6.2 has some updating. See https://docs.generic-mapping-tools.org/latest/changes.html. We may open an issue to manage most updating.

**Comment by seisman** [comment]
I don't want to spend the time going through all the changes. Instead, we can update it when we find any differences between the Chinese and English documentation.
