### ISSUE TITLE
从脚本中删除 pdf,png?

### ISSUE THREAD

**Issue by seisman** [gmt-china/GMT_docs#423]
目前 GMT 手册中的所有（或大部分）脚本，都使用了 `pdf,png` 生成 PDF 和 PNG 格式的两种图片。PNG 图片供网页版使用，PDF 图片供 PDF 文档使用。生成 PDF 的时候也可以使用 PNG 格式的图片，但这会导致最终生成的PDF非常大。现在使用PDF图片，PDF文档是20MB，如果使用PNG图片，我印象中会达到50MB以上。基于这个理由，我认为同时生成两种格式是有必要的。

另一方面，指定 `pdf,png` 存在的问题是:

1. 繁琐
2. 给初学者带来错误的印象。初学者可能会认为 `pdf,png` 是必须的

可能的解决办法：

1. 从所有脚本中删除 `pdf,png`
2. 在构建网页或PDF前，批量在 `gmt begin xxx` 的后面加上 `pdf,png`

**Comment by seisman** [comment]
> 可能的解决办法：
> 
> 1. 从所有脚本中删除 `pdf,png`
> 2. 在构建网页或PDF前，批量在 `gmt begin xxx` 的后面加上 `pdf,png`

不可行

**Comment by wangliang1989** [comment]
> 繁琐
> 给初学者带来错误的印象。初学者可能会认为 pdf,png 是必须的

不觉得繁琐，也不觉得初学者会搞错

**Comment by seisman** [comment]
Closed by e03f030eadfe385aebf508446fd4118e22bbd062.
