### ISSUE TITLE
增加 CN-faults 的更多用法

### ISSUE THREAD

**Issue by seisman** [gmt-china/GMT_docs#428]
@liuzhumei 曾经总结了一套中国断层数据的更详细的使用方法，但我一直没整理进去。有兴趣的可以帮忙整理。

以下是 @liuzhumei 提供的笔记：

## 中国断层数据集

​	本数据集格式为  [OGR/GMT](https://docs.gmt-china.org/6.1/table/ogrgmt/)，属性包括断层名称、长度、走向、倾向、倾角、断层性质、最晚活动年代等。数据集原始来源为邓起东院士等：

- 中文引用

  邓起东, 张培震, 冉勇康, 杨晓平, 闵伟, 陈立春, 2003. 中国活动构造与地震活动, 地学前缘, 10(S1), 66-73.

- 英文引用

  Deng, Q. D., Zhang, P. Z., Ran, Y. K., Yang, X. P., Min, W., Chen, L. C., 2003. Active tectonics and earthquake activities in China. Earth Science Frontiers, 10(S1): 66-73.

### 根据属性信息提取数据

`convert`模块可根据属性筛选某一条/类断层数据，关键选项为`-S`。例如，提取“阿巴宫断裂”数据，可在`-S`选项后加筛选条件（`FAU_NAME=阿巴宫断裂`)，即可输出断层名称为“阿巴宫断裂”的所有数据。`-a`选项表示添加断层名称为输出数据的头信息（`L`表示标注名称），用于`plot`模块中断层名字的显示，详情可参考**（链接）。

```
  gmt begin 
  	gmt convert CN-faults.gmt -S"FAU_NAME=阿巴宫断裂"  -aL=FAU_NAME | gmt plot -R87/90/46/49 -Ba -Sqn1:+Lh+f11,STHeiti-Regular--GB-EUC-H 
  gmt end
```

结果如下：

![image](https://user-images.githubusercontent.com/3974108/122621384-62088f80-d063-11eb-9091-17c517f09f97.png)

### 根据空间范围提取数据

`gmtselect`模块，可实现矩形范围、缓冲区范围和多边形范围内空间数据的提取。

#### 矩形范围提取

在`select`模块中设置`-R`选项，可在矩形区域内筛选数据。例如：

```
  gmt begin 
  	REM 绘制矩形区域
  	echo 110 35 112 36 | gmt plot -R109/113/34/37 -JM15c -Ba -Sr+s -Wblue
  	
	REM 提取区域内断层数据并绘制
  	gmt select -R110/112/35/36 CN-faults.gmt -aL=FAU_NAME | gmt plot-Sqd3c:+Lh+f11,STHeiti-Regular--GB-EUC-H
gmt end
```

结果如下：

![image](https://user-images.githubusercontent.com/3974108/122621406-6f257e80-d063-11eb-94ba-8d821e79ba2a.png)
  
#### 缓冲区范围提取
  
在`select`模块中设置`-C`或`-L`选项，可提取以某(组)点或线为中心，一定半径缓冲区内的数据。例如：
  
```
  REM 圆心
  echo 111 35.5 >center
REM 半径100km的圆域
  echo 111 35.5 200k| gmt plot -SE- -Wblue -fg

  REM 筛选半径为100km内的数据
gmt select CN-faults.gmt -Ccenter+d100k -fg -aL=FAU_NAME | gmt plot -R109/113/34/37 -JM15c -Ba -Sqd3c:+Lh+f11,STHeiti-Regular--GB-EUC-H
```

结果如下：

![image](https://user-images.githubusercontent.com/3974108/122621422-78aee680-d063-11eb-9fd9-dbe2aab3575d.png)

  
#### 多边形范围提取
  
在`select`模块中设置`-F`选项，提取某(组)多边形范围内的数据。例如：
  
```
REM 提取某多边形边界
  gmt convert subEQRegion.gmt -S"subEQRegion=冀鲁豫地震亚区" > polygon
  gmt plot polygon -Ba -Wblue
  
  REM 筛选该多边形内数据
  gmt select CN-faults.gmt -Fpolygon -aL=FAU_NAME | gmt plot -Sqd2c:+Lh+f11,STHeiti-Regular--GB-EUC-H 
  
```
  
结果如下：

![image](https://user-images.githubusercontent.com/3974108/122621437-849aa880-d063-11eb-8c6a-7ec41f608cb2.png)

**Comment by core-man** [comment]
这里主要用法都添加进手册了，还有需要补充的吗？ @liuzhumei
