### ISSUE TITLE
完善按功能分类的GMT模块列表

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#440]
最早提出于 https://github.com/gmt-china/GMT_docs/pull/439#discussion_r654894233

> Do we want to update the following tables based on https://docs.generic-mapping-tools.org/latest/modules.html#session-management in another PR later?

我们需要重新整理一下 [GMT 模块（按功能分类）](https://docs.gmt-china.org/latest/module/) 列表，这里包含的模块也不全。

- [x] main program: #495

**Comment by core-man** [comment]
GMT 官方的按功能分类分得更加细，而中文手册分得比较粗。例如，中文手册将所有绘图模块都放在了**绘图相关模块**，其中`segyz` 和 `segy` 在官方手册里与 `segy2grd` 一同放在 **SEGY** 分类下。**2D 数据处理**里模块众多，不熟悉这些模块的用户想查找具有某功能的模块较为费事。我个人觉得较细的分类更加友好一点。

**Comment by seisman** [comment]
> 我个人觉得较细的分类更加友好一点，因此想在官方分类的基础将模块细分一下。如果没有意见，我会逐渐提交 PR。

OK。在开始细分之前，我建议对现有的分类先做一些简化，主要是两点：

1. 使用 Sphinx 的 simple table 而非 grid table (https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#tables)
2. 由于列表很长，所以建议给每个分类建一个 label，然后在这里使用 `:ref:` 语法建一个分类的列表

![image](https://user-images.githubusercontent.com/3974108/127669403-6c06d825-375e-4107-9885-b9d6fed535ab.png)

**Comment by core-man** [comment]
> OK。在开始细分之前，我建议对现有的分类先做一些简化，主要是两点：
> 
> 1. 使用 Sphinx 的 simple table 而非 grid table (https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#tables)
> 2. 由于列表很长，所以建议给每个分类建一个 label，然后在这里使用 `:ref:` 语法建一个分类的列表

Sound good to me~

**Comment by seisman** [comment]
可以先发一个小PR看看效果，以免效果不好浪费时间。

**Comment by core-man** [comment]
Okay.
