### ISSUE TITLE
cpt文件的位置

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#442]
[cpt文件](https://docs.gmt-china.org/latest/cpt/)这一章在目录的位置可以移动到到**GMT基础**后面，**表数据**之前?并不是表数据和网格数据才需要cpt。而且作为参考书，cpt 文件也没必要放这两个数据后面。

**Comment by seisman** [comment]
移动的理由是什么？

**Comment by core-man** [comment]
> 移动的理由是什么？

我觉得cpt文件实际可以算作属于gmt基础，但是因为其重要性值得level1；英文靠在一块看着更和谐

**Comment by core-man** [comment]
api也可以放在模块后面，一来我们很少看api 二来英文放在后面显得和谐

**Comment by seisman** [comment]
1. 只有在使用表数据和网格数据的时候才需要使用 CPT，所以把 CPT 放在表数据和网格数据后面
2. 任何基础的绘图都需要表格数据和网格数据，但 CPT 不是必须的。所以从基础的角度上来说，表数据和网格数据更基础
3. 模块手册放在最后的一个原因是，模块手册这一部分在PDF中非常长，如果模块手册放在中间会显得很不协调

**Comment by core-man** [comment]
> 只有在使用表数据和网格数据的时候才需要使用 CPT，所以把 CPT 放在表数据和网格数据后面
> 任何基础的绘图都需要表格数据和网格数据，但 CPT 不是必须的。所以从基础的角度上来说，表数据和网格数据更基础

你说的合理，但是从实用性来说，查阅cpt显然比表数据和网格数据要多很多。

> 模块手册放在最后的一个原因是，模块手册这一部分在PDF中非常长，如果模块手册放在中间会显得很不协调

但是API其实很少被查阅

**Comment by core-man** [comment]
Ping @gmt-china/contributors for more comments.

**Comment by wangliang1989** [comment]
我同意core-man说的并不是表数据和网格文件才用到cpt。但是我认为不应该换位置，因此表数据和网格文件比cpt更基础，所以他应该在前面。需要精细地确定颜色就需要cpt文件，所以不妨把cpt文件这一章，改成“颜色与cpt文件”。现在cpt文件这一章最大的问题是内容不全。

**Comment by seisman** [comment]
> 需要精细地确定颜色就需要cpt文件，所以不妨把cpt文件这一章，改成“颜色与cpt文件”。

可以改为 "CPT 颜色表"，CPT 本来就是颜色表的简写，但是在其他绘制软件中，都不称为 CPT，而是 colormap 之类。使用 “CPT 颜色表” 既保留了 GMT 的特色，同时GMT初学者也更容易知道 CPT 是干嘛的。

**Comment by core-man** [comment]
> 我同意core-man说的并不是表数据和网格文件才用到cpt。但是我认为不应该换位置，因此表数据和网格文件比cpt更基础，所以他应该在前面。需要精细地确定颜色就需要cpt文件，所以不妨把cpt文件这一章，改成“颜色与cpt文件”。

> 现在cpt文件这一章最大的问题是内容不全。

这是个好建议。我目前的计划是重新整理一遍手册，我自己的顺序是这样计划的：
- #371 首先修改每章的首页介绍，使得读者阅读每章第一页就知道大概内容
- 然后对重点章节的内容进行整理，比如
  - 安装
  - CPT文件
  - 地学数据集 (如 #300)
  - 模块手册的类别排序 #440
- 最后整理剩余章节

**Comment by seisman** [comment]
> 我同意你们的逻辑，但是我始终觉得不见得一定要按照逻辑的顺序，我们查阅 CPT 文件的机会远多于表数据和网格数据，不是吗？

首先这是一本书，我期望的是，用户可以通过通读全书来学习GMT，所以章节之间的逻辑顺序很重要。

**Comment by seisman** [comment]
@core-man Can we close the issue?
