### ISSUE TITLE
完善 conda 安装

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#452]
**问题描述**

目前跨平台安装 gmt 的方式只有 conda，但是该教程还可以进一步完善。
1.  安装指南的目录顺序：

     官方安装指南 | 中文手册安装指南
     ---|---
     [Windows](https://github.com/GenericMappingTools/gmt/blob/master/INSTALL.md#windows) | [Linux](https://docs.gmt-china.org/latest/install/linux/)
     [macOS](https://github.com/GenericMappingTools/gmt/blob/master/INSTALL.md#macos) | [Windows](https://docs.gmt-china.org/latest/install/windows/)
     [Linux](https://github.com/GenericMappingTools/gmt/blob/master/INSTALL.md#linux) | [macOS](https://docs.gmt-china.org/latest/install/macOS/)
     [Cross-Platform](https://github.com/GenericMappingTools/gmt/blob/master/INSTALL.md#cross-platform-install-instructions) | [跨平台](https://docs.gmt-china.org/latest/install/cross-platform/)
     [FreeBSD](https://github.com/GenericMappingTools/gmt/blob/master/INSTALL.md#freebsd) | [Linux/macOS 下编译GMT源码](https://docs.gmt-china.org/latest/install/build-source/)
     [OpenBSD](https://github.com/GenericMappingTools/gmt/blob/master/INSTALL.md#openbsd) | -

     - 是否需要将 conda 安装放在第一位？conda 安装的优点和缺点如下：
         优点：
       - 一键安装
       - 安装不同版本简单
       - 切换方便
    
       缺点：
       - 需要额外安装 Anconda

     - 另外，由于国内 Windows 用户居多，是否可以将 Windows 的位置移动至 Linux 之前？

2.  完善 conda 安装

     当前 conda 安装部分仅有安装最新 gmt 和升级 gmt 至最新版本。建议增加以下内容：
     - 添加安装和切换其他版本，如 gmt 5
     - 添加安装最新dev版本
     - 增加安装 Anaconda 安装和使用教程，或直接添加[seismo-learn/software/Anaconda](https://seismo-learn.org/software/anaconda/)链接

**系统信息**

* 操作系统：
* GMT 版本（`gmt --version`）：

**Comment by wangliang1989** [comment]
对于anaconda的重度用户，这种安装方式是有吸引力的。我建议conda的安装直接链接seismo-learn

**Comment by seisman** [comment]
>    * 是否需要将 conda 安装放在第一位？conda 安装的优点和缺点如下：
>      优点：
>      
>      * 一键安装
>      * 安装不同版本简单
>      * 切换方便

不需要，对于大部分非Python用户而言，用 anaconda 安装是一件很麻烦的事情。

>    * 另外，由于国内 Windows 用户居多，是否可以将 Windows 的位置移动至 Linux 之前？

No, 整个手册的内容都是以 Linux 为主。

> 2. 完善 conda 安装
>    当前 conda 安装部分仅有安装最新 gmt 和升级 gmt 至最新版本。建议增加以下内容：
>    
>    * 添加安装和切换其他版本，如 gmt 5

No, 不考虑 GMT 5

>    * 添加安装最新dev版本

可以

>    * 增加安装 Anaconda 安装和使用教程，或直接添加[seismo-learn/software/Anaconda](https://seismo-learn.org/software/anaconda/)链接
> 

可以直接链接
