### ISSUE TITLE
gmtwhich 的 -Ga 选项

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#454]
**问题描述**

gmtwhich 的 -Ga 选项解释有问题？

[-G[a|c|l|u]](https://docs.gmt-china.org/latest/module/gmtwhich/#g):
> 使用该选项，若GMT在当前目录或本地缓存目录中未找到文件，则会尝试下载。
> - -Gl 表示下载到当前目录（默认行为）
> - -Ga 表示由GMT自动决定该数据应下载到哪个目录
> - -Gu 表示下载到用户数据目录
> - -Gc 表示下载到用户缓存目录

[GMT 官方: -G](https://docs.generic-mapping-tools.org/latest/gmtwhich.html#g):
> If a file argument is a downloadable file (either a complete URL, a @file for downloading from the GMT data server, or @earth_relief_xxy) we will try to download the file if it is not found in your local data or cache dirs. By default [-Gl] we download to the current directory. Append a to place files in the appropriate folder under the user directory (this is where GMT normally places downloaded files), c to place it in the user cache directory, or u for the user data directory instead (i.e., ignoring any subdirectory structure).

-Ga 表示的是 `user directory`，而不是由GMT自动决定该数据应下载到哪个目录？

**Comment by seisman** [comment]
> the appropriate folder under the user directory

这句话包含了子目录。如果是 earth_relief 文件，则放在 `~/.gmt/server` 下，如果是一般 cache 文件，则放在 `~/.gmt/cache` 下

**Comment by core-man** [comment]
> we will try to download the file if it is not found in your local data or cache dirs

这句话的意思是走一遍：`当前目录 > GMT 用户目录 > GMT 数据目录 > GMT 缓存目录` + `~/.gmt/server` 的意思吗？
还是走一遍 `~/.gmt/server` 和 GMT 缓存目录？

**Comment by seisman** [comment]
```
$ gmt which @earth_relief_01d -Vd
...
gmtwhich [DEBUG]: Look for file earth_relief_01d_p.grd in /Users/seisman/.gmt
gmtwhich [DEBUG]: Look for file earth_relief_01d_p.grd in /Users/seisman/.gmt/data,/Users/seisman/Gits/gmt-china/china-geospatial-data
gmtwhich [DEBUG]: Look for file earth_relief_01d_p.grd in /Users/seisman/.gmt/cache
gmtwhich [DEBUG]: Look for file earth_relief_01d_p.grd in /Users/seisman/.gmt/server
...
```

```
$ gmt which abc -Vd
gmtwhich [DEBUG]: Look for file abc in /Users/seisman/.gmt
gmtwhich [DEBUG]: Look for file abc in /Users/seisman/.gmt/data,/Users/seisman/Gits/gmt-china/china-geospatial-data
gmtwhich [DEBUG]: Look for file abc in /Users/seisman/.gmt/cache
gmtwhich [DEBUG]: Look for file abc in /Users/seisman/.gmt/server
```

严格来说，在搜缓存目录之后，还会搜 server 目录，但是这个在整个GMT文档里应该都没提到。估计是默认用户不会向 server 目录下随便加文件。

**Comment by core-man** [comment]
> 严格来说，在搜缓存目录之后，还会搜 server 目录，但是这个在整个GMT文档里应该都没提到。估计是默认用户不会向 server 目录下随便加文件。

good~ 那是走 `当前目录 > GMT 用户目录 > GMT 数据目录 > GMT 缓存目录 + ~/.gmt/server` 流程。目前英文文档只是用了` local data or cache dirs` 来描述.
