### ISSUE TITLE
“学习资源”中“GMT 中文手册：入门教程”的链接失效

### ISSUE THREAD

**Issue by seisman** [gmt-china/GMT_docs#463]
**问题描述**

“学习资源”(https://docs.gmt-china.org/latest/intro/resources/) 这一节的“GMT 中文手册: 入门教程” 链接失效。见下图：

![image](https://user-images.githubusercontent.com/3974108/123465430-1eaaa580-d5bc-11eb-8ac3-ebdaf6298580.png)

失效的原因是因为在 https://github.com/gmt-china/GMT_docs/pull/461 中， `source/tutorial/index.rst` 文件并重命名了。

**解决方法：**

将其改完 "GMT 中文手册：入门教程 和 进阶教程"，并分别链接到 https://github.com/gmt-china/GMT_docs/blob/master/source/tutorial/started.rst 和 https://github.com/gmt-china/GMT_docs/blob/master/source/tutorial/advanced.rst。

具体语法可以参考 https://seismo-learn.org/contributing/restructuredtext/#id8

**Comment by core-man** [comment]
@ZMAlt, 这个issue是否可以帮忙处理一下呢？正好也可以顺便熟悉一下流程。

**Comment by ZMAlt** [comment]
> @ZMAlt, 这个issue是否可以帮忙处理一下呢？正好也可以顺便熟悉一下流程。

我最近没得空了。可能要过段时间才能有空。

**Comment by core-man** [comment]
> > @ZMAlt, 这个issue是否可以帮忙处理一下呢？正好也可以顺便熟悉一下流程。
> 
> 我最近没得空了。可能要过段时间才能有空。

好的，等你有空的时候，若这个 issue 还没被认领的话，可以直接提交 PR 解决此 issue。

**Comment by ZMAlt** [comment]
有空了，搞一下

**Comment by core-man** [comment]
> 有空了，搞一下

Great~
