### ISSUE TITLE
“中国及邻区地质图数据”脚本的注释改为英文

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#466]
**问题描述**

[中国及邻区地质图数据](https://docs.gmt-china.org/latest/dataset-CN/geo3al/) 中的 [示例图](https://docs.gmt-china.org/latest/dataset-CN/geo3al/#id2) 脚本 [geo3al.sh](https://github.com/gmt-china/GMT_docs/blob/master/source/dataset-CN/geo3al/geo3al.sh) 的中注释中英混杂，建议统一为中文注释。
例如，`Plot the geological map by geologic ages` -->> `按照地质年代绘制地质图`

```
#!/usr/bin/env bash
#
# 中国及邻区地质图
#

data=geo3al.gmt
cpt=geoage.cpt

gmt begin geo3al pdf,png
    # 绘制陆地为白色，即灰度 255
    gmt coast -R70/150/13/55 -JM22c -G255 -Baf -BWsNe

    # Plot the geological map by geologic ages
    # -aZ="GEN_GLG": use the "GEN_GLG" metadata as the Z value
    # -G+z -C$cpt: the fill color is determined by the Z value and the CPT file
    gmt plot $data -C$cpt -aZ="GEN_GLG" -G+z

    # Plot rock types using diffenrent patterns (28, 29 and 44)
    # -aI="TYPE": using the "TYPE" metadata as ID
    # -S"-Iv": only keep data segments that matches "-Iv" (v means "Volcanic rocks")
    # -S"-Ii": only keep data segments that matches "-Ii" (i means "Intrusive rocks")
    # -S"-Iw": only keep data segments that matches "-Iw" (w means "Ultrabasic igneous rock or ophiolites")
    # -Gp28+r500+f100+b-: fill with pattern 28, dpi=500, foreground color=100 (gray), background color=- (transparent)
    gmt convert $data -aI="TYPE" -S"-Iv" | gmt plot -Gp28+r500+f100+b-
    gmt convert $data -aI="TYPE" -S"-Ii" | gmt plot -Gp29+r500+f100+b-
    gmt convert $data -aI="TYPE" -S"-Iw" | gmt plot -Gp44+r500+f100+b-

    # 绘制海洋或者湖泊为 CADETBLUE1 颜色
    gmt coast -SCADETBLUE1

    # Plot geologic age legend
    gmt set FONT_ANNOT_PRIMARY 7p  # font for legend labels
    cat > age_legend.txt << EOF
H 10 3 Age of rock units
N 3
EOF
    # Output non-empty lines that don't start with "B", "F", "N" or "#"
    gawk '!/^($|B|F|N|#)/' $cpt | while read label color period
    do
        echo "S 0.3c r 0.38c $color 0.3p 0.7c $period" >> age_legend.txt
    done
    gmt legend age_legend.txt -DJBR+w10.5c+jTR+o0c/-2c+l1.3 -F+p0.7p+g255 -C3p/3p
    rm age_legend.txt

    # Plot rock type legend
    gmt legend -DJBR+w5.0c+jBR+o0c/2c+l1.9 -F+p0.7p+g255 -C3p/1p <<EOF
H 10 3 Rock type
N 2
S 0.3c r 0.5c p28+r500+f100+b255 0.3p 0.7c Volcanic rocks
S 0.3c r 0.5c p29+r500+f100+b255 0.3p 0.7c Intrusive rocks
S 0.3c r 0.5c p44+r500+f100+b255 0.3p 0.7c Ultrabasic igneous rock or ophiolites
EOF
gmt end show
```

**Comment by seisman** [comment]
我更倾向于脚本中的注释统一使用英文，原因如下:

1. 简单英文，大家都能懂
2. 纯英文，脚本复制粘贴之后是 ASCII 码，而不是 UTF8，对于 Windows 用户也许更友好
3. 据我所知，是有些外国人通过google翻译看GMT中文手册的。正文里的中文翻译没问题，但是代码中的中文没法翻译

**Comment by core-man** [comment]
> 我更倾向于脚本中的注释统一使用英文，原因如下:
> 
> 1. 简单英文，大家都能懂
> 2. 纯英文，脚本复制粘贴之后是 ASCII 码，而不是 UTF8，对于 Windows 用户也许更友好
> 3. 据我所知，是有些外国人通过google翻译看GMT中文手册的。正文里的中文翻译没问题，但是代码中的中文没法翻译

sounds good to me

**Comment by ZMAlt** [comment]
Tutorial 里的注释几乎都是中文。是整体改呢？还是说各章节分开来？

**Comment by core-man** [comment]
> Tutorial 里的注释几乎都是中文。是整体改呢？还是说各章节分开来？

这个 issue 只要改 “中国及邻区地质图数据”脚本的注释改为英文即可。

其他地方单独提几个 PR 改吧，这样方便审稿和接收。最好每个 PR 只是改某一章或某一小节，比如 [理解图层](https://docs.gmt-china.org/latest/tutorial/layers/) 这个小节就可以单独改。

**Comment by ZMAlt** [comment]
我的意思是，是整个文档以后都改成英文注释吗？还是只这一部分。我觉得 tutorial 改成英文不太友好。

**Comment by core-man** [comment]
> 我的意思是，是整个文档以后都改成英文注释吗？还是只这一部分。我觉得 tutorial 改成英文不太友好。

应该是整个文档。简单的英文注释大家还是可以看得懂的，如果注释较为复杂，则应考虑将注释放在正文中描述。

我大概浏览了以下，tutorial 里貌似只需要改  [理解图层](https://docs.gmt-china.org/latest/tutorial/layers/), [GMT图中图模式](https://docs.gmt-china.org/latest/tutorial/inset/), [GMT多图模式](https://docs.gmt-china.org/latest/tutorial/multifig/) 这几个小节。[脚本编程](https://docs.gmt-china.org/latest/tutorial/scripting/) 和 [命令初探](https://docs.gmt-china.org/latest/tutorial/commands/) 还是保留中文比较好。

**Comment by seisman** [comment]
> 简单的英文注释大家还是可以看得懂的，如果注释较为复杂，则应考虑将注释放在正文中描述。

Yes.
