### ISSUE TITLE
“中国及邻区地质图数据”的图例用colorbar绘制？

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#477]
**问题描述**

最早提出于 https://github.com/gmt-china/GMT_docs/pull/364#issuecomment-863741049:

> 原脚本里用 pslegend 画矩形的方式画了图例，我尝试直接用 colorbar 画了一下，也可以画，但是加标题和边框没那么方便，还需要调整:
>
> ```
> gmt begin colorbar png
> gmt coast -R70/150/13/55 -JM8.6i -Baf -Df -> G255 -BWsNe
> gmt set MAP_FRAME_PEN 0.3p
> gmt colorbar -Cgeoage.cpt -Dx0c/0c+w-5c/0.5c -L0.1 -G0/15
> gmt colorbar -Cgeoage.cpt -Dx5c/0c+w-4.667c/0.5c -L0.1 -G16/29
> gmt colorbar -Cgeoage.cpt -Dx10c/0c+w-4.667c/0.5c -L0.1 -G30/43
> gmt end show
> ```
> ![image](https://user-images.githubusercontent.com/3974108/122504306-0a691600-cfc8-11eb-94c2-44b0dd3bd664.png)
>
> 我不确定哪种方式更好，感觉原脚本里用了awk之类的有点复杂，而上面的 colorbar 也需要调更多的参数才能得到类似的效果。

当前，[geo3al: 中国及邻区地质图数据](https://docs.gmt-china.org/latest/dataset-CN/geo3al/#id2)的实例图采用 [legend](https://docs.gmt-china.org/latest/module/legend/)模块绘制图例，也可以使用[colorbar](https://docs.gmt-china.org/latest/module/colorbar/)模块绘制。

Ping @xumi1993 @seisman for comments as I never used `legend`.

**Comment by seisman** [comment]
我现在觉得原始的方式可能是最简单的方式。用 colorbar 可以实现，但是复杂的地方在于:

1. 原图里有37个矩形块，无法等分为三份，只能分成 13, 12, 12 三份。在使用 colorbar 的时候，colorbar 的长度就得按照比例设置（比如 13c, 12c, 12c），否则会导致每一列的矩形高度不一样，变得很丑
2. 原图例里的标题和边框，只能通过 basemap 和 text 实现，反而变得不够自动化了
