### ISSUE TITLE
更新"地理空间数据格式转换"

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#500]
## 问题描述

最早提出于 https://github.com/gmt-china/GMT_docs/issues/303#issuecomment-869138745:

> > [GDAL/OGR: 地理空间数据格式转换神器](https://gmt-china.org/blog/gdal-ogr/)

> 此博客是否适合移入[用ogr2ogr实现数据转换](https://docs.gmt-china.org/latest/table/ogr2ogr/)？ 

[中国地理空间数据集](https://docs.gmt-china.org/latest/dataset-CN/) 的建立和处理流程经常使用 `org2ogr` 命令。有必要将社区博客并入中文手册 [用ogr2ogr实现数据转换](https://docs.gmt-china.org/latest/table/ogr2ogr/) 中？

**Comment by core-man** [comment]
`ogr2ogr` 相关的其他章节如下：

- [表数据：index](https://docs.gmt-china.org/latest/table/)
- [Shapefile格式](https://docs.gmt-china.org/latest/table/shapefile/)
- [OGR/GMT矢量数据格式](https://docs.gmt-china.org/latest/table/ogrgmt/)

**Comment by seisman** [comment]
> 是否维护该命令？维护的话，也放在 `utilities` 目录下？还是将这两个命令放在同一个页面，就像现在博客那样？我建议分开。

我建议放在一起。GDAL 提供了很多命令，ogr2ogr 和 gdal_translate 只是其中最常用的两个，以后也可能会介绍其它命令。而且这两个命令的用法其实都很短（我们只做简要介绍），没必要分成多节。

**Comment by core-man** [comment]
> > 是否维护该命令？维护的话，也放在 `utilities` 目录下？还是将这两个命令放在同一个页面，就像现在博客那样？我建议分开。
> 
> 我建议放在一起。GDAL 提供了很多命令，ogr2ogr 和 gdal_translate 只是其中最常用的两个，以后也可能会介绍其它命令。而且这两个命令的用法其实都很短（我们只做简要介绍），没必要分成多节。

Okay to me.
