### ISSUE TITLE
添加“Google Maps 超高精度高程数据”至“自定义数据”

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#502]
## 问题描述

最早提出于 https://github.com/gmt-china/GMT_docs/issues/303#issuecomment-870399386:

> > [利用 Google Maps 获取超高精度高程数据](https://gmt-china.org/blog/google-maps-elevation-api/)

> 目前 GMT 的地形起伏数据最高精度是为 1 弧秒（约 30米），而 Google Maps Elevation API 提供了米级精度。

> 我觉得可以放入进阶教程和自定义数据中：
> - #476 中计划增加“如何提取和绘制剖面”的进阶教程，里面包含了地形起伏剖面教程
> - Google Maps Elevation API 提取米级精度地形起伏数据的方法可以收入[自定义数据](https://docs.gmt-china.org/latest/dataset/#id3)中

建议将“Google Maps 超高精度高程数据”的简介和提取方法添加至“自定义数据”中，方便用户使用超高精度高程数据？

**Comment by seisman** [comment]
重新看了一下这一节，感觉没有必要再进一步整理，主要原因如下：

1. 我原以为 Google Maps Elevation 的数据精度是 1 m 量级，但实际上数据精度在不同地方是不同的，以教程中的示例结果为例
```
{
   "results" : [
        {
            "elevation" : 1608.637939453125,
            "location" : {
                "lat" : 39.73915360,
                "lng" : -104.98470340
            },
            "resolution" : 4.771975994110107
        }
   ],
   "status" : "OK"
}
```
该点位于美国，resolution 是 4.77 m。合理的猜测是美国的地形分辨率是最高的，其它地方分辨率不会高于5m，所以与 GMT 提供的 30m 精度差别不是太大。

2. Google 相关服务在国内使用有困难
3. 使用 Google Elevation API 需要生成 API key，而生成 API key 需要提供信用卡信息并可能需要美国手机号（猜测是因为Google不直接对中国提供服务），而且后台比较复杂，我摸索了一下也没搞清楚再哪里生成 API key

综上，感觉不值得花时间整理这一篇博文到手册里。

**Comment by core-man** [comment]
Sound good~
