### ISSUE TITLE
将Vscode添加到windows安装指南的可选安装软件里

### ISSUE THREAD

**Issue by CovMat** [gmt-china/GMT_docs#507]
将Vscode添加到windows安装指南的可选安装软件里，放在gitbash之前，作为推荐编辑器。是否可行？

**Comment by core-man** [comment]
> 将Vscode添加到windows安装指南的可选安装软件里，放在gitbash之前，作为推荐编辑器。是否可行？

那样的话还需要同时安装gitbash吗？

**Comment by CovMat** [comment]
gitbash也可以不用安装，这两个没什么关系

**Comment by core-man** [comment]
> gitbash也可以不用安装，这两个没什么关系

okay. 可以
