### ISSUE TITLE
UnixTools 工具包源文件

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#508]
## 问题描述

最初提出于: https://github.com/gmt-china/GMT_docs/pull/506#discussion_r662747120

> 建议将该工具包转移至手册中，当前该工具包位于社区网站仓库中。毕竟只有 300 多kb。

> 还是放在原处不动吧，以后再考虑怎么做更合适。

**UniTools** 工具包的简介已经在 #506 中由 [中文社区博客](https://gmt-china.org/blog/unix-tools-for-windows/) 转移至 [中文手册](https://docs.gmt-china.org/latest/install/windows/#id1) 中维护。

工具包源文件 `UnixTools.zip` 还在社区网站仓库下:  https://github.com/gmt-china/gmt-china.org/tree/master/content/data. 建议移动至手册中或者其他地方维护。

**Comment by seisman** [comment]
想了一下，还是把 UnixTools 移动过来吧。

**Comment by core-man** [comment]
> 想了一下，还是把 UnixTools 移动过来吧。

放在 `source/install` 目录下？ 并将 https://github.com/gmt-china/GMT_docs/blob/master/source/install/windows.rst 的  `UnixTools.zip <https://gmt-china.org/data/UnixTools.zip>` 修改为 `UnixTools.zip`
