### ISSUE TITLE
img2google 模块翻译

### ISSUE THREAD

**Issue by ZMAlt** [gmt-china/GMT_docs#510]
#469

**Comment by core-man** [comment]
欢迎持续翻译和贡献. 是否可以把你加入 [contributors](https://github.com/orgs/gmt-china/teams/contributors) team. 这样的话，你可以直接提交修改至 GMT-china 的仓库，不必修改你的 forked 仓库了，而且你的修改可以直接在线预览。比如 https://github.com/gmt-china/GMT_docs/pull/509#issuecomment-872776591:

> This comment was written by the Continuous Documentation bot!
> Preview: https://gmt-china.github.io/sitepreview/gmt-china/GMT_docs/vscode/index.html
> Commit hash: 1364c18

点击那个链接就可以在线预览提交的 PR 的修改效果.

参考 https://github.com/gmt-china/china-geospatial-data/pull/48#issuecomment-870519894.

**Comment by ZMAlt** [comment]
当前可以，很荣幸！

**Comment by core-man** [comment]
> 当前可以，很荣幸！

已邀请～你接受后，clone 一下 GMT-china 的 GMT_docs 仓库至你的本地计算机，以后就不需要你的 GitHub 的 forked 仓库了。

**Comment by core-man** [comment]
@ZMAlt 请在三个已翻译的module中添加你的名字作为贡献者。

**Comment by core-man** [comment]
> @ZMAlt 请在三个已翻译的module中添加你的名字作为贡献者。

Ping @ZMAlt again in case you forgot it.

**Comment by ZMAlt** [comment]
ok, 前几天比较忙
