### ISSUE TITLE
更新“快速链接”中的“投影方式”链接

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#514]
## 问题描述

[快速链接](https://docs.gmt-china.org/latest/) 中的 **投影方式** 指向 [-J 选项](https://docs.gmt-china.org/latest/option/J/)，是否将其改为指向 [地图投影](https://docs.gmt-china.org/latest/proj/)。因为用户并不关心哪种指定投影的方式，而主要关心具体的投影代码。此外，第一个快速链接，即**标准选项**，已经包含了 -J 选项。

## 解决办法

[快速链接](https://docs.gmt-china.org/latest/) ： `投影方式 </option/J>` 改为 `地图投影 </proj/index>`

**Comment by core-man** [comment]
Shall we @seisman?

**Comment by seisman** [comment]
OK
