### ISSUE TITLE
删除“快速链接”中的“引用 GMT”链接 

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#515]
**问题描述**

[快速链接](https://docs.gmt-china.org/latest/) 中的 **引用 GMT** 应该只在写论文的时候需要用到，平时不需要查询。是否可以删除？因为很容易想到可以[简介](https://docs.gmt-china.org/latest/intro/)中查询。

**Comment by seisman** [comment]
暂时保留吧。目前4行三列正好。如果以后有其他链接要加再考虑替换掉

**Comment by seisman** [comment]
快捷链接中还有空间，暂时无需考虑删除“引用 GMT”的问题。
