### ISSUE TITLE
更新“安装”

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#519]
## 问题描述

[GMT 安装](https://docs.gmt-china.org/latest/install/) 这一章对于刚接触 GMT 的新手是最重要的一步。当前章节的排版需要美化，且部分内容需要修改或更新。

- [ ] [Linux 下安装 GMT](https://docs.gmt-china.org/latest/install/linux/)
- [ ] [Windows 下安装 GMT](https://docs.gmt-china.org/latest/install/windows/)： #512
- [ ] [macOS 下安装 GMT](https://docs.gmt-china.org/latest/install/macOS/)
- [ ] [跨平台安装 GMT](https://docs.gmt-china.org/latest/install/cross-platform/)： #518
- [ ] [Linux/macOS 下编译GMT源码](https://docs.gmt-china.org/latest/install/build-source/)
- [ ] Windows 下 GMT 源码编译安装

建立此 Issue 来追踪和汇总相关修改。

**Comment by core-man** [comment]
See https://github.com/gmt-china/GMT_docs/pull/512#discussion_r666563212:
> I can't say I like the layout of this subsection, but we can improve it later.

Windows 下安装 GMT 的 [脚本工具](https://docs.gmt-china.org/latest/install/windows/#id2) 还需要完善。

**Comment by core-man** [comment]
当前 Windows 下安装 GMT 的方式有两种：
- 通过 Windows 安装包安装：适用于纯 Windows 用户
- conda 安装：适用于 Windows 下的 anaconda 用户 

其实 Windows 用户另外一个选择是安装 WSL[推荐]、双系统、虚拟机，在 Linux 下安装和使用 GMT。我们是否在 **Windows 下安装 GMT** 一节提示新用户可以做如此选择？ Ping @gmt-china/contributors and @liuzhumei for comments，特别是 Windows 用户。

**Comment by liuzhumei** [comment]
> 手册中详细描述的 Windows 下安装 GMT 的方式有两种：
> 
> * 通过 Windows 安装包安装：适用于纯 Windows 用户
> * conda 安装：适用于 Windows 下的 anaconda 用户
> 
> 其实 Windows 用户另外一个选择是安装 WSL[推荐]、双系统、虚拟机，在 Linux 下安装和使用 GMT。我们是否在 **Windows 下安装 GMT** 这一节开头提示新用户可以有如此选择？我不知道 Windows 下的 Linux 用户到底有多大比例，还是大部分都是纯 Windows 或 Windows 下的 anaconda 用户。
> 
> Ping @gmt-china/contributors and @liuzhumei for comments，特别是 Windows 用户。

windows下用WSL的用户画像是怎样的? 曾经 @seisman 做过一个问卷调查，我记得纯windows用户比例很大。

**Comment by seisman** [comment]
> 其实 Windows 用户另外一个选择是安装 WSL[推荐]、双系统、虚拟机，在 Linux 下安装和使用 GMT。我们是否在 Windows 下安装 GMT 这一节开头提示新用户可以有如此选择？

我不觉得我们应该这样做。

1. Windows 用户如果只是想使用 GMT 的话，完全没有必要用WSL、双系统或者虚拟机
2. 在 Windows 下使用 Linux 的用户（WSL、双系统或虚拟机），应该知道自己本质上使用的是 Linux，那么安装软件也应该按照 Linux 的方式去安装

**Comment by seisman** [comment]
Close the issue?
