### ISSUE TITLE
macOS下homebrew安装GMT的方法需要更新

### ISSUE THREAD

**Issue by seisman** [gmt-china/GMT_docs#52]
1. gmt已经从homebrew/science中移到了 homebrew/core 中
2. homebrew的gmt4和gmt不再存在冲突，但安装两个之后只能使用GMT5版本
3. 是否可能修改gmt的formulae使得其安装时支持额外的选项

**Comment by seisman** [comment]
1. 已解决
2. 解决办法: 手动删除GMT5的bin目录下的软链接并将GMT4的路径添加到PATH中
3. 已修改，但homebrew-core拒绝了PR

**Comment by wangliang1989** [comment]
我试验的情况，和你不同
brew install gmt
brew install gmt4
安装以后，可以直接正常调用psxy，但gmt是打开的gmt4，而不是gmt5。我现在是先brew安装gmt5，然后自己编译安装gmt4，解决了，应该是没有问题

**Comment by seisman** [comment]
请卸载 gmt 和 gmt4，并重新安装gmt和gmt4，然后将 gmt --version 和 psxy - 的输出贴出来。

**Comment by wangliang1989** [comment]
我刚刚没说完整，我做的事是
brew install gmt
brew install gmt4
brew uninstall  gmt4
按这个装gmt4: http://seisman.info/install-gmt4-under-mac.html
输出是：
![image](https://user-images.githubusercontent.com/12059719/34761110-5a6bca9a-f61d-11e7-9c3a-63342dd34ce8.png)

**Comment by seisman** [comment]
http://seisman.info/install-gmt4-under-mac.html 你是按照这篇文章的做法手动编译的GMT4?

**Comment by wangliang1989** [comment]
对啊

**Comment by seisman** [comment]
这样做可以，但是使问题复杂化了，并不是最优的解决办法。

**Comment by wangliang1989** [comment]
http://gmt.soest.hawaii.edu/projects/gmt/wiki/Installing
我试了官方的做法，不行，效果是输入gmt，用的是gmt4

**Comment by seisman** [comment]
官方做法已经过时。

**Comment by wangliang1989** [comment]
你直说该怎么做啊

**Comment by seisman** [comment]
我已经说了啊 ``手动删除GMT5的bin目录下的软链接并将GMT4的路径添加到PATH中``

**Comment by wangliang1989** [comment]
我试了不行，无效，不然我就不会重开这个issue了

**Comment by seisman** [comment]
没有给出详细信息，无法判断。

**Comment by wangliang1989** [comment]
就是我把bin下的软连接删除后，一切照旧。输入psxy调用的gmt4成功，但是输入gmt，打开的是gmt4，不是gmt5

**Comment by seisman** [comment]
1. `brew install gmt`
2. `brew install gmt4`
3. 删除GMT5带的软链接:
    ```
    cd /usr/local/opt/gmt@5/bin
    find . -size -4c -delete       # 删除所有文件大小小于4字节的软链接
    ```

4. 删除GMT4的多余文件：
    ```
    cd /usr/local/opt/gmt@4/bin
    rm GMT
    ```

**Comment by wangliang1989** [comment]
还需要
brew install ghostscript
