### ISSUE TITLE
更新“中文支持”

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#520]
## 问题描述

[中文支持](https://docs.gmt-china.org/latest/chinese/) 这一章的国内用户需求较大。当前章节的排版需要美化，且部分内容需要修改或更新。

- [x] [Linux 下的 GMT 中文支持](https://docs.gmt-china.org/latest/chinese/linux/) (#974 )
- [x] [macOS 下的 GMT 中文支持](https://docs.gmt-china.org/latest/chinese/macOS/) (#974)
- [ ] [Windows 下的 GMT 中文支持](https://docs.gmt-china.org/latest/chinese/windows/)
- [x] [GMT中文效果演示](https://docs.gmt-china.org/latest/chinese/showcase/) (#1005 )
- [x] [自定义字体原理](https://docs.gmt-china.org/latest/chinese/custom-fonts/) (#974)
- [x] #571
- [x] 源码编译的中文支持

建立此 Issue 来追踪和汇总相关修改。此 Issue 与 #519 的相关章节可能需要综合考虑，比如 #512 就涉及到安装 GMT 过程中的中文支持问题。

**Comment by core-man** [comment]
See https://github.com/gmt-china/GMT_docs/pull/512#discussion_r665284313:

>> 这里应该是 cidfmap 吧?

> 也许吧，ghostscript 是有 cidmap 和 cidfmap 的，我不确定这里显示的到底是哪一个。

这部分内容在 #512 中被移动至 [Windows 下的 GMT 中文支持: ghostscript 的中文支持](https://docs.gmt-china.org/latest/chinese/windows/)，需要进一步确认和完善。

**Comment by BerginJay** [comment]
更新了 macOS 下中文支持的内容 #796

**Comment by liuzhumei** [comment]
[Windows 下的 GMT 中文支持:GMT中文测试](https://docs.gmt-china.org/latest/chinese/windows/#id1)中关于  `chcp 936` 命令的添加位置应改为 “**每句使用中文的命令之前**”，因为一旦再次写一个 `gmt...` 图层，编码又自动变回去了。 若连续的使用 `echo`命令输出文件，则不需要重复写 `chcp 936` ，因为没有使用 `gmt`命令。 @CovMat

**Comment by CovMat** [comment]
> [Windows 下的 GMT 中文支持:GMT中文测试](https://docs.gmt-china.org/latest/chinese/windows/#id1)中关于 `chcp 936` 命令的添加位置应改为 “**每句使用中文的命令之前**”，因为一旦再次写一个 `gmt...` 图层，编码又自动变回去了。 若连续的使用 `echo`命令输出文件，则不需要重复写 `chcp 936` ，因为没有使用 `gmt`命令。 @CovMat

明白，马上改
