### ISSUE TITLE
统一 bash shebang

### ISSUE THREAD

**Issue by seisman** [gmt-china/GMT_docs#527]
目前某些脚本的 shebang 依然是 `#!/bin/bash`，更推荐的 shebang 是 `#!/usr/bin/env bash`。

可以使用 `sed` 命令批量搜索替换。

**Comment by ZMAlt** [comment]
Fixed

**Comment by seisman** [comment]
@ZMAlt 还有一些地方用的是 `#!/bin/bash` 没改的，比如 `basis/escapes.sh`

**Comment by ZMAlt** [comment]
什么意思？我本地的这个文件是改了的， #530 里的 file changed 的这个文件也是改了的。 grep 也找不到没改的文件

**Comment by seisman** [comment]
Sorry，是我看错了，同步 master 的时候失败了，所以以为这些文件都还没改。
