### ISSUE TITLE
更新地形起伏数据的缓存

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#533]
## 问题描述

为了绘图更快，我们使用 [cache-data.yml](https://github.com/gmt-china/GMT_docs/blob/master/.github/workflows/cache-data.yml) 缓存较大的数据。目前地形起伏的缓存需要更新。

### 低分辨率地形起伏的缓存

[cache-data.yml](https://github.com/gmt-china/GMT_docs/blob/master/.github/workflows/cache-data.yml) 目前缓存了以下低分辨率地形起伏数据：

https://github.com/gmt-china/GMT_docs/blob/86bbfd9beb5f6ae55358e49eb625f08a217f7af7/.github/workflows/cache-data.yml#L34-L38

**不要再缓存的数据：**
- 中文手册中并不使用 `earth_relief_20m` 绘制图片。因此不需要缓存 `earth_relief_20m` 了，删掉该行即可。
- #532 中将入门教程中“理解图层”一节 (https://docs.gmt-china.org/latest/tutorial/layers/) 从 10 弧分 ( `earth_relief_10m`) 的地形数据降低为 30 弧分 (`earth_relief_30m`) 分辨率。其他章节也未使用 10 弧分的分辨率画图。因此不需要缓存 `earth_relief_10m` 了，删掉该行即可。

---

- `earth_relief_05m` 分辨率用于附录中的“等值线标注和“线条标注” (https://docs.gmt-china.org/latest/contour-annot/) 的“综合实例”中: `gmt grdgradient @earth_relief_05m -R-85/5/10/55 -Nt1 -A45 -Gtopo5_int.nc`
- `earth_relief_30m` 分辨率用于绘制全球地形
- `earth_relief_06m` 分辨率用于"绘制三维地形图"实例 (https://docs.gmt-china.org/latest/examples/ex029/). 

---

### 高分辨率地形起伏的缓存

https://github.com/gmt-china/GMT_docs/blob/86bbfd9beb5f6ae55358e49eb625f08a217f7af7/.github/workflows/cache-data.yml#L44

#531 中将入门教程中“绘制地形起伏”一节 (https://docs.gmt-china.org/latest/tutorial/earth-relief) 的“绘图区域地形起伏图”使用的分辨率从 `earth_relief_30s` 降低为  `earth_relief_01m`。

其他章节也未使用 `earth_relief_30s` 画图。

因此，`earth_relief_30s` 需要改为 `earth_relief_01m`

**Comment by seisman** [comment]
我建议缓存所有 06m 及更低分辨率的地形数据，因为这部分数据很小，全部缓存下来也方便以后改来改去。

对于 05m 及更高分辨率的数据，则根据需要进行缓存。

**Comment by core-man** [comment]
> 我建议缓存所有 06m 及更低分辨率的地形数据，因为这部分数据很小，全部缓存下来也方便以后改来改去。

你是指 https://docs.gmt-china.org/latest/dataset/earth-relief/ 所有的 06m 及以上？

> 对于 05m 及更高分辨率的数据，则根据需要进行缓存。

Okay.

**Comment by seisman** [comment]
> 你是指 [docs.gmt-china.org/latest/dataset/earth-relief](https://docs.gmt-china.org/latest/dataset/earth-relief/) 所有的 06m 及以上？

是，单指 earth_relief，其他数据用的比较少，按需缓存即可。
