### ISSUE TITLE
中文手册和官方手册的全球地形起伏数据大小不一致

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#534]
## 问题描述

[中文手册](https://docs.gmt-china.org/latest/dataset/earth-relief/) | [官方手册](https://docs.generic-mapping-tools.org/latest/datasets/remote-data.html#global-earth-relief-grids)
--- | ---
![GMT-china](https://user-images.githubusercontent.com/50591376/124550222-f136e500-de62-11eb-92fa-d0f3558d0f19.png) | ![GMT](https://user-images.githubusercontent.com/50591376/124550223-f1cf7b80-de62-11eb-84e5-610f66120064.png)

我在本地测试跟以上两个手册也不同。

```
$ du -s  earth_relief_30m_p.grd  
396K     earth_relief_30m_p.grd

$ du -h earth_relief_20m_p.grd                     
832K	earth_relief_20m_p.grd

$ du -h earth_relief_10m_p.grd                     
3.1M	earth_relief_10m_p.grd

$ du -h earth_relief_06m_p.grd                     
8.0M	earth_relief_06m_p.grd
```

USTC 数据服务器 (http://mirrors.ustc.edu.cn/gmt/data/) 的大小又不一样。

**Comment by seisman** [comment]
我建议这里的文件大小直接改成一个约数即可，比如不写 112 KB，而写成约 100 KB。

没人关心文件的具体大小，大家在意的只是大概的量级而已。

**Comment by seisman** [comment]
> USTC 数据服务器 ([http://mirrors.ustc.edu.cn/gmt/data](http://mirrors.ustc.edu.cn/gmt/data/)) 的大小又不一样。

这里的数据已经过时，留在这里只是为了兼容 GMT5 用户。

GMT6用户所使用的数据实际上来源于 https://mirrors.ustc.edu.cn/gmtdata/

**Comment by core-man** [comment]
> GMT6用户所使用的数据实际上来源于 https://mirrors.ustc.edu.cn/gmtdata/

使用 USTC mirror 数据的大小更新地形起伏数据的大小，使用约数 （如 121 kb -> 100 kb; 189 kb -> 200 kb）？
