### ISSUE TITLE
GMT初探：Bash 脚本文件

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#535]
## 问题描述

GMT初探: [Linux 篇](https://docs.gmt-china.org/latest/tutorial/get-started/linux/#) 和 [macOS篇](https://docs.gmt-china.org/latest/tutorial/get-started/macos/) 中的 Bash 例子中：

```Bash
#!/usr/bin/env -S bash -e
# GMT modern mode bash template
# Date:    2019-09-10T00:44:39
# User:    seisman
# Purpose: Purpose of this script
export GMT_SESSION_NAME=$$  # Set a unique session name
gmt begin figurename
    gmt coast -Rg -JH15c -Gpurple -Baf -B+t"My First Plot"
gmt end show
```

`-S` 和 `-e` 选项不需要加了吧？

**Comment by seisman** [comment]
这是GMT生成的模板

**Comment by core-man** [comment]
为何第一个没有 `-S` and `-e`? 统一？

![](https://user-images.githubusercontent.com/50591376/124601964-fb74d580-de9a-11eb-9ba5-5b52d4328e92.png)

**Comment by seisman** [comment]
> 统一为 GMT 的输出版模板？

OK.

**Comment by core-man** [comment]
第一个 bash 模板开头改为 `#!/usr/bin/env -S bash -e`.
