### ISSUE TITLE
更新 source/scripts

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#537]
## 问题描述

`source/scripts` 包含了一些脚本和文件：

```
$ ls source/scripts
combined_logo.sh  GMT_basemap_origin.sh  GMT_contour-anno6.sh  GMT_patterns.sh            Makefile     plot_-Sw.sh        text_-M.sh
cpt_cyclic.sh     GMT_contour-anno1.sh   GMT_contour-anno7.sh  GMT_stand+_iso+.sh         plot_-A.sh   plot_symbols.sh    transect.txt
cross.txt         GMT_contour-anno2.sh   GMT_contour-anno8.sh  GMT_symbol_dingbats.sh     plot_-F.sh   polar_ex1.sh       ttt_atl.nc
fitcircle_ex1.sh  GMT_contour-anno3.sh   GMT_contour-anno9.sh  GMT_text_justification.sh  plot_-L.sh   project_sketch.sh  ttt.cpt
gcircle.txt       GMT_contour-anno4.sh   GMT_CPT_3.sh          great_NY_Canaries.txt      plot_-Sf.sh  scircle.txt        velo_ex1.sh
geoid.nc          GMT_contour-anno5.sh   GMT_CPT_4.sh          great_NY_Paris.txt         plot_-Sm.sh  text_clearance.sh  velo_ex2.sh
```

我还没具体看每个文件和脚本，但是是否可以将其放如对应章节中？ 例如，`GMT_contour-anno[1-8].sh` 放入 [等值线标注和“线条标注”](https://docs.gmt-china.org/latest/contour-annot/).

**Comment by seisman** [comment]
历史遗留问题，很多脚本都可以移到对应章节的目录下。

**Comment by seisman** [comment]
部分脚本其实可以删了，比如 GMT_patterns.sh, GMT_stand+_iso+.sh, GMT_symbol_dingbats.sh。这三个用于生成 `source/image` 下对应的图片文件，然而这些图片文件几乎从来都不会改变的，所以这三个脚本也就没用了。

需要重新生成图片的时候，直接从GMT官方文档里复制图片更加简单。

**Comment by core-man** [comment]
提交三个 PR 依次删除以下三个脚本，并将 `source/images` 下对应的图片文件移动只相应的中文手册目录下。
- [ ] GMT_patterns.sh
  - `source/images/GMT_patterns.*` 图片
  - 中文手册：https://docs.gmt-china.org/latest/basis/fill/#id3
  - GMT 官方手册：https://docs.generic-mapping-tools.org/latest/cookbook/predefined-patterns.html
- [ ] GMT_stand+_iso+.sh
  - `source/images/GMT_stand+_iso+.*` 图片
  - 中文手册：https://docs.gmt-china.org/latest/basis/special-character/#id2
  - GMT 官方手册：https://docs.generic-mapping-tools.org/latest/cookbook/octal-codes.html#chart-of-octal-codes-for-characters
- [ ] GMT_symbol_dingbats.sh
  - `source/images/GMT_stand+_iso+.*` 图片
  - 中文手册：https://docs.gmt-china.org/latest/basis/special-character/#id3
  - GMT 官方手册：https://docs.generic-mapping-tools.org/latest/cookbook/octal-codes.html#chart-of-octal-codes-for-characters

**Comment by core-man** [comment]
以下列表会持续更新。建议每次单独移动一个章节对应的脚本或文件。

- [ ] `GMT_contour-anno[1-8].sh` 放入 [等值线标注和“线条标注”](https://docs.gmt-china.org/latest/contour-annot/) ：
  - 在 `/source` 下新建一个 `contour-annot` 目录；
  - 将 `GMT_contour-anno[1-8].sh` 移动至该目录下；
  - 将 `/source/contour-annot.rst` 移动至该目录下，并重命名为 /source/contour-annot/index.rst`;
  - 更新 `/source/index.rst`

**Comment by core-man** [comment]
Merge `combined_logo.sh` into https://github.com/gmt-china/logo/blob/master/mklogo.sh?

**Comment by core-man** [comment]
I cannot find where `GMT_basemap_origin.sh` and `GMT_text_justification.sh` are used.
