### ISSUE TITLE
删除 image_optimize.sh?

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#580]
## 问题描述

我们已经使用 GitHub Action 了，还需要保留 `ci/image_optimize.sh` 吗？

See https://github.com/seismo-learn/seismology101/issues/358#issuecomment-875698697:

> The script was used before we migrated the CI service from Travis to GitHub Actions.

> The GMT_Docs repository cannot use the image-actions because most of the images in the GMT_Docs are generated by the gmtplot directive. Thus, these images are not added in the repository and image-actions won't optimize them.

**Comment by seisman** [comment]
Closed by #608
