### ISSUE TITLE
plot3d 模块翻译

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#590]
## 问题描述

[plot3d](https://docs.generic-mapping-tools.org/6.2/plot3d.html) 模块用于绘制伪 3D 的符号与线段，在手册实例[绘制三维地形图](https://docs.gmt-china.org/latest/examples/ex029/)中使用过一次。

鉴于其的实用性，因此在众多尚未翻译整理的模块中具有较高的优先级  (见 #469)。

**Comment by seisman** [comment]
Closed by https://github.com/gmt-china/GMT_docs/issues/713.
