### ISSUE TITLE
gmtconvert 模块翻译

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#591]
## 问题描述

[gmtconvert](https://docs.generic-mapping-tools.org/6.2/gmtconvert.html) 模块用于从数据表中转换、粘贴或提取列。

在构建[中国地理空间数据集](https://docs.gmt-china.org/latest/dataset-CN/)过程中使用频繁，因此在众多尚未翻译整理的模块中具有较高的优先级  (见 #469)。

**Comment by seisman** [comment]
Closed by https://github.com/gmt-china/GMT_docs/issues/713.
