### ISSUE TITLE
“中文社区QQ群入群须知”迁移至附录？

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#600]
## 问题描述

最早提出于 https://github.com/gmt-china/GMT_docs/issues/303#issuecomment-879357421:

> [GMT中文社区QQ群入群须知](https://gmt-china.org/blog/community-guide/) 放入 [学习资源](https://docs.gmt-china.org/latest/intro/resources/) 或者附录里？然后在 https://gmt-china.org/#contact 加上链接。

**Comment by seisman** [comment]
这并不属于中文手册的内容。

**Comment by core-man** [comment]
> 这并不属于中文手册的内容。

那在社区主页的联系我们的qq号旁边加上这篇博文的链接？要不然很少人会注意到这个博文吧。

同理，中文手册学习资源一节的qq号也备注一下这个博文的链接？

**Comment by seisman** [comment]
> 那在社区主页的联系我们的qq号旁边加上这篇博文的链接？要不然很少人会注意到这个博文吧。
> 
> 同理，中文手册学习资源一节的qq号也备注一下这个博文的链接？

OK
