### ISSUE TITLE
GMT相关工具

### ISSUE THREAD

**Issue by seisman** [gmt-china/GMT_docs#615]
我的想法是，将GMT相关工具作为附录的单独一章。目前我认为“GMT相关工具”包括：

- [ ] VSCode: https://github.com/gmt-china/GMT_docs/pull/599
- [x] GDAL/OGR: https://github.com/gmt-china/GMT_docs/issues/500
- [ ] Google Maps 高精度地形： https://github.com/gmt-china/GMT_docs/issues/502

**Comment by core-man** [comment]
oaky~

**Comment by core-man** [comment]
GMT相关工具的目录英文叫 gmt-utilities 如何？

**Comment by seisman** [comment]
直接叫tools或者utilities即可

**Comment by core-man** [comment]
> 直接叫tools或者utilities即可

okay. let's use utilities.

**Comment by wangliang1989** [comment]
我建议增加python等语言如何调用gmt的语法例子

**Comment by seisman** [comment]
关于 VScode 的问题，我细想了一下。

目前 VSCode 的介绍位于 https://gmt-china.org/blog/vscode-usage/。原计划将 VSCode 移动到 GMT 手册中的相关工具一节（#599），但会存在两个问题：

1. 严格来说 VSCode 并不是 GMT 相关工具，所以稍微有点偏离主题
2. 博文中使用的 gif 图片无法在手册的 PDF 版本中正常显示

基于以上两点，我认为将 VSCode 移动到手册里不是一个好的选择。

后来考虑到 seismo-learn 里也会介绍 VSCode，所以进一步将 VSCode 的介绍移动到了 seismology101 中 (https://github.com/seismo-learn/seismology101/pull/404)，这同样存在如下问题：

1. 尽管 seismology101 目前没有提供 PDF 版本，但未来可能会提供，加入 gif 图片使得生成 PDF 不再可能
2. 原 VSCode 博文中的一些内容与 GMT 深度相关，而 seismology101 中是将 vscode 作为一个通用的文本编辑器或脚本执行器来使用的，不需要介绍在编辑器中预览图片等功能。因而，原 vscode 博文的内容并不适合 seismology101。

我目前的想法是，将 vscode 保留在 gmt-china.org 中，不进行迁移。

**Comment by wangliang1989** [comment]
> 关于 VScode 的问题，我细想了一下。
> 
> 目前 VSCode 的介绍位于 [https://gmt-china.org/blog/vscode-usage/。原计划将](https://gmt-china.org/blog/vscode-usage/%E3%80%82%E5%8E%9F%E8%AE%A1%E5%88%92%E5%B0%86) VSCode 移动到 GMT 手册中的相关工具一节（#599），但会存在两个问题：
> 
> 1. 严格来说 VSCode 并不是 GMT 相关工具，所以稍微有点偏离主题
> 2. 博文中使用的 gif 图片无法在手册的 PDF 版本中正常显示
> 
> 基于以上两点，我认为将 VSCode 移动到手册里不是一个好的选择。
> 
> 后来考虑到 seismo-learn 里也会介绍 VSCode，所以进一步将 VSCode 的介绍移动到了 seismology101 中 ([https://github.com/seismo-learn/seismology101/pull/404)，这同样存在如下问题：](https://github.com/seismo-learn/seismology101/pull/404)%EF%BC%8C%E8%BF%99%E5%90%8C%E6%A0%B7%E5%AD%98%E5%9C%A8%E5%A6%82%E4%B8%8B%E9%97%AE%E9%A2%98%EF%BC%9A)
> 
> 1. 尽管 seismology101 目前没有提供 PDF 版本，但未来可能会提供，加入 gif 图片使得生成 PDF 不再可能
> 2. 原 VSCode 博文中的一些内容与 GMT 深度相关，而 seismology101 中是将 vscode 作为一个通用的文本编辑器或脚本执行器来使用的，不需要介绍在编辑器中预览图片等功能。因而，原 vscode 博文的内容并不适合 seismology101。
> 
> 我目前的想法是，将 vscode 保留在 gmt-china.org 中，不进行迁移。

我认为并没有偏离主题，因为完全没有基础的人，他真的需要知道编辑器的事情。gif不能显示，就不用gif的表达形式即可。或者给一个链接，让他上线看
