### ISSUE TITLE
重新设计首页内容

### ISSUE THREAD

**Issue by seisman** [gmt-china/GMT_docs#618]
https://docs.gmt-china.org/latest/

该页面目前包含了如下内容：

- logo
- 手册的简单介绍
- 手册的学习指南
- 指向视频教程的图片
- 快捷链接
- 招募志愿者的广告

对于纯新手，视频教程和学习指南有用；对于非新用户而言，快捷链接更有用。而目前该页面内容过多，对于正常尺寸的笔记本而言，需要滚动页面才能看到快捷链接，使用起来极为不便。

我的建议是：

1. 删除视频教程图片，可以在“手册学习指南”的第一点中直接给一个链接即可
2. logo 缩小
3. 或许可以删除“招募志愿者的广告”

**Comment by seisman** [comment]
Ping @core-man @CovMat

**Comment by core-man** [comment]
> 删除视频教程图片，可以在“手册学习指南”的第一点中直接给一个链接即可

okay

> logo 缩小

okay

> 或许可以删除“招募志愿者的广告”

okay. [README.md](https://github.com/gmt-china/GMT_docs) 中也有广告了。
