### ISSUE TITLE
“贡献指南”中增加“绘图实例投稿”小节？

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#624]
## 问题描述

是否在中文手册的 [贡献指南](https://docs.gmt-china.org/latest/contributing/) 中新建一个小节，讲述社区博文 [投稿须知](https://gmt-china.org/blog/instructions-for-authors/) 中的 **示例的要求** 以及社区的 `CONTRIBUTING` 的 [**新增示例**](https://github.com/gmt-china/gmt-china.org/blob/master/CONTRIBUTING.md#%E6%96%B0%E5%A2%9E%E7%A4%BA%E4%BE%8B)？

然后再对 [投稿须知](https://gmt-china.org/blog/instructions-for-authors/) 和 [`CONTRIBUTING`](https://github.com/gmt-china/gmt-china.org/blob/master/CONTRIBUTING.md#%E6%96%B0%E5%A2%9E%E7%A4%BA%E4%BE%8B) 进行更新。

**Comment by seisman** [comment]
OK
