### ISSUE TITLE
html_extra_path entry 'CNAME' does not exist

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#627]
## 问题描述

本地编译 `make html` 警告，与 #617 中删除 `CNAME` 有关:

```
WARNING: html_extra_path entry 'CNAME' does not exist
```

https://github.com/gmt-china/GMT_docs/blob/8eef143ac067cf090607bc76af8c3e22dcfc68e9/source/conf.py#L82

**Comment by seisman** [comment]
可以删除
