### ISSUE TITLE
GMT 6.2 开始支持 LaTeX

### ISSUE THREAD

**Issue by seisman** [gmt-china/GMT_docs#667]
GMT 自 6.2 开始支持 LaTeX，这一部分内容尚未加入到中文手册中。

- https://blog.seisman.info/gmt-latex/ (GMT 6.2 之前无 LaTeX 支持时的解决方案）
- https://docs.generic-mapping-tools.org/latest/cookbook/gmt-latex.html (GMT 6.2 的 LaTeX 用法）

**Comment by ZMAlt** [comment]
还没有人做的话，我来？

**Comment by core-man** [comment]
> 还没有人做的话，我来？

Great, please.
