### ISSUE TITLE
“表数据”和“网格文件”并为一章

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#674]
## 问题描述

这个问题之前貌似私下讨论过，这里我想再次讨论合并的好处：

- 二者都是关于 GMT 的数据文件的格式，有很多共同点。例如，GDAL 的支持（见 [OGR/GMT矢量数据格式](https://docs.gmt-china.org/latest/table/ogrgmt/#id1) **简介**）。如果二者合并为一章，可以在 index 中统一介绍二者，而不是像现在这样把二者的比较和汇总放在 **OGR/GMT矢量数据格式** 这一小节。
- 我们在相关工具一章中会详细介绍 GDAL/OGR (#500)，这里使用的 `ogr2ogr` 和 `gdal_translate` 与表数据和网格数据是直接相关的。合并后，GDAL/OGR 小节和合并后的章节就一一对应，有利于读者理解和查阅。

如果合并的话，章节构成的样子可以参考[地学数据集](https://docs.gmt-china.org/latest/dataset/)。表数据和网格文件目前的小节放在对应的**表数据**（如**内置数据**）和**网格文件**（如**远程数据**）标题下，还可以新增其他共同小节（如简介）。

![](https://user-images.githubusercontent.com/50591376/126131281-fbb51284-73f6-4b95-968a-dd7ac73152fc.png)

**Comment by seisman** [comment]
我不支持合并，理由是：

1. 这两章每章都已经有很多内容了，合并之后只会使得这一章变得更长
2. 这两类数据之间几乎没有共同点。GDAL对于处理表数据是有用的，但是对于处理网格文件几乎用不到。所有需要用到 gdal_translate 的地方，几乎都可以用GMT自己的 grdgdal 来代替
