### ISSUE TITLE
增加 explain_-F_box 和 explain_refpoint 

### ISSUE THREAD

**Issue by ZMAlt** [gmt-china/GMT_docs#688]
[修饰物](https://docs.gmt-china.org/6.2/basis/embellishment/#)里的[参考点](https://docs.gmt-china.org/6.2/basis/embellishment/#id3)和[背景面板](https://docs.gmt-china.org/6.2/basis/embellishment/#id8)在模块里用的挺多的，我们是不是把他们子选项的解释单独作为两个文件，方便模块翻译？

### 官方文件
参考点 explain_refpoint.rst_  <https://github.com/GenericMappingTools/gmt/blob/master/doc/rst/source/explain_refpoint.rst_>
背景面板 explain_-F_box.rst_ <https://github.com/GenericMappingTools/gmt/blob/master/doc/rst/source/explain_-F_box.rst_>

**Comment by seisman** [comment]
可以
