### ISSUE TITLE
A bug for -Js projection?

### ISSUE THREAD

**Issue by core-man** [gmt-china/GMT_docs#691]
## 问题描述

以下两句的区别是加不加 `-BN`，不加的话不绘制北面的边框，显示指出才会绘制。

```
gmt coast -R-180/180/-90/-60 -Js0/-90/12c/-60 -Bafg -BN -Dl -Ggrey -pdf GMT_stereographic_polar
```

![GMT_stereographic_polar](https://user-images.githubusercontent.com/50591376/126996240-29aeb200-fcfa-4328-9ac3-2687e9fdb540.png)

```
gmt coast -R-180/180/-90/-60 -Js0/-90/12c/-60 -Bafg -Dl -Ggrey -png GMT_stereographic_polar
```

![GMT_stereographic_polar](https://user-images.githubusercontent.com/50591376/126996348-86371fa4-5519-428c-9ee6-50512895319b.png)

---

貌似是一个BUG？

https://docs.generic-mapping-tools.org/latest/cookbook/features.html#auto-scaling:
>  MAP_FRAME_AXES | Axes that are drawn and annotated

**Comment by seisman** [comment]
不太确定，看上去有点像bug。可以报给 gmt 确认一下。

**Comment by ZMAlt** [comment]
6.2 的-B 选项似乎有点问题，最开始是群里的用户发现的。我好像没在官方文档看到相关的描述

```
gmt basemap -R0/4/0/4 -JX4c -BWSEN -png axes
```
单行模式 `-BWSEN` 没有标注 
![axes](https://user-images.githubusercontent.com/35285040/128959197-8f8c64f2-ebf2-46ea-85c8-a099df0bb5ec.png)

----

现代模式 `-BWSEN` 没有标注 
```
gmt begin test1 png
    gmt basemap -R0/4/0/4 -JX4c -BWSEN
gmt end show
```
![test1](https://user-images.githubusercontent.com/35285040/128959731-909b154b-4f0b-483e-9ffa-5246f99eb640.png)

---

现代模式放到 subplot 里 `-BWSEN` 有标注
```
gmt begin test1 png
gmt subplot begin 1x7 -Fs4c/4c -M5p/10p
    gmt basemap -R0/4/0/4 -JX4c -BWSEN
gmt subplot end
gmt end show
```
![test1](https://user-images.githubusercontent.com/35285040/128959674-246af11d-2b50-4703-8a87-5773181741cd.png)

**Comment by seisman** [comment]
加了 -Baf 都会显示，不太好确认是不是 bug。

**Comment by seisman** [comment]
@ZMAlt @core-man 我建议你们像 GMT 官方报 bug。

**Comment by ZMAlt** [comment]
第一个问题在当前版本已经不存在。
第二个和 subplot 相关的问题等官方 issue。
先关闭
