### ISSUE TITLE
将 gdal 列为必须包，而非可选包？

### ISSUE THREAD

**Issue by seisman** [gmt-china/GMT_docs#692]
所有分辨率高于 05m 的 earth_relief 数据都是以 jp2 格式保存在服务器上，待数据下载完成后再调用 gdal_translate 将 jp2 转换为 netcdf 保存在本地。

因而，尽管严格来说 gdal 是可选包，但实际上 GMT 已经开始严重依赖 GDAL，我觉得最好将其修改为必须包。

**Comment by core-man** [comment]
okay~

**Comment by seisman** [comment]
在 #704 中，将 GDAL 列为 **推荐** 安装的包。
