### ISSUE TITLE
GMT的MATLAB接口

### ISSUE THREAD

**Issue by seisman** [gmt-china/GMT_docs#7]
1. http://gmt.soest.hawaii.edu/doc/5.2.1/matlab_wrapper.html
2. http://gmt.soest.hawaii.edu/projects/gmt-matlab-octave-api/wiki
3. http://gmt.soest.hawaii.edu/projects/gmt/repository/show/trunk/doc/scripts/ml

**Comment by liuzhumei** [comment]
接口在windows下的用法，我尝试做一下。

**Comment by seisman** [comment]
Finished in #33.

**Comment by seisman** [comment]
TODO:

- [ ] 提供配套的 matlab 脚本
- [ ] 用 psconvert 生成PNG 和 PDF 图片
