### ISSUE TITLE
Edit on GitHub 不能正确链接

### ISSUE THREAD

**Issue by zhaozhiyuan1989** [gmt-china/GMT_docs#70]
Edit on GitHub 链接莫名其妙的少了个 edit
正确链接应为：
https://github.com/gmt-china/GMT_Docs/edit/master/source/index.rst
实际链接为：
https://github.com/gmt-china/GMT_Docs//master/source/index.rst

**Comment by zhaozhiyuan1989** [comment]
SAC 手册同

**Comment by seisman** [comment]
可能是哪里有修改导致的，你要不要尝试修一下？

**Comment by seisman** [comment]
Related to https://github.com/rtfd/sphinx_rtd_theme/pull/617
