### ISSUE TITLE
-B 选项更新

### ISSUE THREAD

**Issue by ZMAlt** [gmt-china/GMT_docs#726]
gmt 6.2 对 -B 选项的处理发生了变化，中文文档目前有点滞后，需要更新下

**Comment by ZMAlt** [comment]
等 https://github.com/gmt-china/GMT_docs/issues/691#issuecomment-896450203 解决后再更新

**Comment by seisman** [comment]
没有必要等 #691，可以直接更新 -B 选项的其他部分。

**Comment by ZMAlt** [comment]
已经更新了一部分。先放一下，最近没什么空了
