### ISSUE TITLE
w选项的文档有编译错

### ISSUE THREAD

**Issue by wangliang1989** [gmt-china/GMT_docs#749]
https://github.com/gmt-china/GMT_docs/blob/master/source/option/w.rst

表格有语法错，导致不能通过编译（报错没有截完）：
![image](https://user-images.githubusercontent.com/12059719/132041536-0a8e0bc7-963e-4b90-b821-0d8b8479c95d.png)
另外语句不太通顺。

@ZMAlt @core-man @seisman

**Comment by wangliang1989** [comment]
还有很多语句不通顺

**Comment by seisman** [comment]
> 还有很多语句不通顺

Will be addressed in https://github.com/gmt-china/GMT_docs/issues/605.

**Comment by ZMAlt** [comment]
> 还有很多语句不通顺

嗯，不是很好翻译，有些我自己念着也不舒服。

暂时没得空，先放一放吧。
