### ISSUE TITLE
one-line command应该翻译为单行命令而不是单行模式

### ISSUE THREAD

**Issue by wangliang1989** [gmt-china/GMT_docs#751]
https://github.com/GenericMappingTools/gmt/issues/5745

如果你们同意，我可以来修改并完善相关叙述

**Comment by seisman** [comment]
你对这些东西的理解有误。

**Comment by wangliang1989** [comment]
> 你对这些东西的理解有误。

中文手册没有说，我才会理解错，不想修改下吗？

**Comment by seisman** [comment]
GMT 官方文档使用的是 oneliner，中文手册中翻译为单行模式。

单行命令并不是一个好的翻译，因为任何命令均可以称之为单行命令，比如 `cat data.txt`, `gmt basemap -R0/10/0/10 -JX10c -Baf` 都是单行命令。

而 oneliner 专指形如 `gmt basemap -R0/10/0/10 -JX10c -Ba -pdf map` 这样的命令，因而“单行模式”是更恰当的翻译。

**Comment by wangliang1989** [comment]
使用gmt命令绘图有三种模式：

1. 经典模式：语法和gmt5一致
2. 现代模式：采用gmt6语法，以模块begin开始，end结尾
3. 单行模式：采用gmt6语法，-pdf等结尾，单条命令

经典模式、现代模式和单行模式是针对gmt绘图而言的。gmt命令中很多并不是绘图，这些命令无所谓这三种模式

以上理解对吗？
@seisman

**Comment by seisman** [comment]
> 经典模式、现代模式和单行模式是针对gmt绘图而言的。gmt命令中很多并不是绘图，这些命令无所谓这三种模式

可以这样理解，但实际上有些数据处理命令在现代模式下与经典模式下的行为也会有不一致，比如 makecpt 在经典模式下会打印 CPT 文件，在现代模式下则会生成隐藏的“当前CPT”。

**Comment by wangliang1989** [comment]
你这句话里的经典模式其实应该叫gmt5风格，而现代模式是gmt6风格
> 可以这样理解，但实际上有些数据处理命令在现代模式下与经典模式下的行为也会有不一致，比如 makecpt 在经典模式下会打印 CPT 文件，在现代模式下则会生成隐藏的“当前CPT”。

这就是我的另外一个不理解的地方。
假设我想用某一个模块，单条命令，做一些不是画图的事情，比如你说的makecpt，或者regress直线拟合，亦或是histogram对数值的分布进行统计，我认为只要我用的模块名是gmt6的名字，它就该按照gmt6的语法风格，然而似乎有时这样，而有时不这样

**Comment by seisman** [comment]
不是，抛开单行模式不谈。经典模式与现代模式的区别在于命令是否在 `gmt begin` 和 `gmt end` 之间执行。如果是，则命令运行在现代模式下，否则命令运行在经典模式下。与模块名并没有任何关系。

**Comment by wangliang1989** [comment]
> 不是，抛开单行模式不谈。经典模式与现代模式的区别在于命令是否在 `gmt begin` 和 `gmt end` 之间执行。如果是，则命令运行在现代模式下，否则命令运行在经典模式下。与模块名并没有任何关系。

假设我想用histogram模块统计输入值的分布，如果在使用的时候，它在begin和end之间，就会是现代模式，否则就是经典模式，也就要用gmt5语法，要叫pshistogram才行？

**Comment by seisman** [comment]
> 假设我想用histogram模块统计输入值的分布，如果在使用的时候，它在begin和end之间，就会是现代模式，否则就是经典模式，也就要用gmt5语法，要叫pshistogram才行？

是

**Comment by wangliang1989** [comment]
一条gmt命令是三种模式中的哪一个的判断标准：

1. 现代模式：该命令在begin和end之间。
2. 单行模式：该命令不在begin和end之间，且用-pdf、-png等结尾。
3. 经典模式：该命令不在begin和end之间，且没有用-pdf、-png等结尾。

现代模式和单行模式应当使用gmt6语法，经典模式用gmt5语法。单行模式肯定是绘图，而现代模式和经典模式可能是绘图，也可能是数据处理、统计等

以上说法正确吧？正确的话，我就抽空写进手册，你看写哪里合适？@seisman

**Comment by seisman** [comment]
文档目前只考虑现代模式，不考虑经典模式。对于用户而言，只要认为所有命令都需要在 `gmt begin` 和 `gmt end` 中执行即可。

单行模式不过是特殊情况下的现代模式的简化写法。经典模式不再提及。

**Comment by liuzhumei** [comment]
> 一条gmt命令是三种模式中的哪一个的判断标准：
> 
> 1. 现代模式：该命令在begin和end之间。
> 2. 单行模式：该命令不在begin和end之间，且用-pdf、-png等结尾。
> 3. 经典模式：该命令不在begin和end之间，且没有用-pdf、-png等结尾。
> 
> 现代模式和单行模式应当使用gmt6语法，经典模式用gmt5语法。单行模式肯定是绘图，而现代模式和经典模式可能是绘图，也可能是数据处理、统计等
> 
> 以上说法正确吧？正确的话，我就抽空写进手册，你看写哪里合适？@seisman

强烈反对把以上内容写进手册。纠结这些东西太容易把初学者绕到沟里去。在我的认识里，经典模式只是6对5兼容的一个接口，我写脚本不会再去考虑这个可能，只会在现代模式（多行），单行模式（一个图层做测试用）中选择。

**Comment by wangliang1989** [comment]
> > 一条gmt命令是三种模式中的哪一个的判断标准：
> > 
> > 1. 现代模式：该命令在begin和end之间。
> > 2. 单行模式：该命令不在begin和end之间，且用-pdf、-png等结尾。
> > 3. 经典模式：该命令不在begin和end之间，且没有用-pdf、-png等结尾。
> > 
> > 现代模式和单行模式应当使用gmt6语法，经典模式用gmt5语法。单行模式肯定是绘图，而现代模式和经典模式可能是绘图，也可能是数据处理、统计等
> > 以上说法正确吧？正确的话，我就抽空写进手册，你看写哪里合适？@seisman
> 
> 强烈反对把以上内容写进手册。纠结这些东西太容易把初学者绕到沟里去。在我的认识里，经典模式只是6对5兼容的一个接口，我写脚本不会再去考虑这个可能，只会在现代模式（多行），单行模式（一个图层做测试用）中选择。

如果你要用gmt的某一个模块做一件和画图无关的事呢？比如histogram模块做统计

**Comment by liuzhumei** [comment]
> > > 一条gmt命令是三种模式中的哪一个的判断标准：
> > > 
> > > 1. 现代模式：该命令在begin和end之间。
> > > 2. 单行模式：该命令不在begin和end之间，且用-pdf、-png等结尾。
> > > 3. 经典模式：该命令不在begin和end之间，且没有用-pdf、-png等结尾。
> > > 
> > > 现代模式和单行模式应当使用gmt6语法，经典模式用gmt5语法。单行模式肯定是绘图，而现代模式和经典模式可能是绘图，也可能是数据处理、统计等
> > > 以上说法正确吧？正确的话，我就抽空写进手册，你看写哪里合适？@seisman
> > 
> > 
> > 强烈反对把以上内容写进手册。纠结这些东西太容易把初学者绕到沟里去。在我的认识里，经典模式只是6对5兼容的一个接口，我写脚本不会再去考虑这个可能，只会在现代模式（多行），单行模式（一个图层做测试用）中选择。
> 
> 如果你要用gmt的某一个模块做一件和画图无关的事呢？比如histogram模块做统计

我只做统计不画图的时候不会使用GMT。换句话说，我使用GMT的唯一目的就是画出图来，histogram是为画图服务的，所以我的命令必然是多行的，那就一定会使用gmt begin/end这种形式。

**Comment by seisman** [comment]
> 如果你要用gmt的某一个模块做一件和画图无关的事呢？比如histogram模块做统计

最简单的方式是，忘记经典模式，始终使用 `gmt begin` 和 `gmt end`，即便你只执行一行 GMT 命令。

同时使用经典模式和现代模式，但是又不理解二者本质区别以及底层原理，就会导致你现在遇到的困惑，以及未来其它的一堆困惑。

**Comment by wangliang1989** [comment]
因为我用perl，所以碰到了经典模式。我当时是想用histogram做统计，我又不想用文件的形式输入数据，而采用标准输入后，perl似乎就没办法捕捉gmt的输出，所以我用echo向gmt输出。这样似乎导致，另开了一个终端，使得histogram命令进入了经典模式

**Comment by seisman** [comment]
> 因为我用perl，所以碰到了经典模式。我当时是想用histogram做统计，我又不想用文件的形式输入数据，而采用标准输入后，perl似乎就没办法捕捉gmt的输出，所以我用echo向gmt输出。这样似乎导致，另开了一个终端，使得histogram命令进入了经典模式

把你的命令贴出来

**Comment by seisman** [comment]
你应该用:
```
system("gmt begin");
open(GMT, "| gmt histogram xxx");
print GMT "xxx";
close(GMT);
system("gmt end");
```

**Comment by wangliang1989** [comment]
> 你应该用:
> 
> ```
> system("gmt begin");
> open(GMT, "| gmt histogram xxx");
> print GMT "xxx";
> close(GMT);
> system("gmt end");
> ```
这样perl得不到gmt的输出

**Comment by seisman** [comment]
> > 你应该用:
> > ```
> > system("gmt begin");
> > open(GMT, "| gmt histogram xxx");
> > print GMT "xxx";
> > close(GMT);
> > system("gmt end");
> > ```
> 
> 这样perl得不到gmt的输出

那是因为你学艺不精。

**Comment by wangliang1989** [comment]
> > > 你应该用:
> 
> > > ```
> 
> > > system("gmt begin");
> 
> > > open(GMT, "| gmt histogram xxx");
> 
> > > print GMT "xxx";
> 
> > > close(GMT);
> 
> > > system("gmt end");
> 
> > > ```
> 
> > 
> 
> > 这样perl得不到gmt的输出
> 
> 
> 
> 那是因为你学艺不精。

你有办法就说出来，也许你认为你有办法但是实际不行

**Comment by seisman** [comment]
我不用perl很多年啦。perl一定有方法可以向命令输入数据同时捕捉命令的输出，如果没有，那就是perl的设计缺陷，因为这是非常常用的需求。

**Comment by seisman** [comment]
Closing the issue because we won't update any descriptions.
