### ISSUE TITLE
change modules' names for gmt6

### ISSUE THREAD

**Issue by wangliang1989** [gmt-china/GMT_docs#80]
need to change modules' names for  @gmt6.

All works about it please try to merge into #82

- [x] psxy => plot
- [x] psxyz => plot3d
- [x] psscale => colorbar
- [x] pscoast => coast
- [x] psconvert 
- [x] ps2raster 
- [x] pssolar
- [x] psbasemap 
- [x] psclip
- [x] pshistogram
- [x] pstext
- [x] pslegend
- [x] psrose
- [x] pssac
- [x] psmeca
- [x] pspolar
- [x] psvelo
- [x] pscoupe
- [x] psimage
- [x] pscontour
- [x] pssegy
- [x] pssegyz
- [x] pswiggle

**Comment by wangliang1989** [comment]
can anyone fix this one? I do not know how to deal with isolation-mode. @seisman 

`source/appendix/isolation-mode.rst:28:    gmt pscoast -R -J -O -Dc -A5000 -Gwhite -Bx60g30 -By30g30 >> $ps`

**Comment by seisman** [comment]
Fixed in #79
