### ISSUE TITLE
sandwell重力异常模型在中国大陆是基于哪个模型？

### ISSUE THREAD

**Issue by zhuuuuuym** [gmt-china/GMT_docs#805]
## 问题描述

你好，我在GMT中文社区 <https://docs.gmt-china.org/6.2/module/img2grd/> 看到您编写的文档模板，现在我想请教的问题是，我在这个网站上下载的sandwell重力异常数据 <https://topex.ucsd.edu/pub/global_grav_1min/>，版本是V31，精度是1min，但是是基于哪个模型的呢？是EGM2008嘛？另外就是该数据在海域的数据精度高，在大陆地区有没有什么优势呀
谢谢

**Comment by ZMAlt** [comment]
Sandwell 的海洋重力场是从卫星测高数据反演得到的。卫星测高在陆地回波很少，所以他的重力场在陆地是没有数据的，所以说不上在陆地没有优势，本本就是没有数据。

最新的模型我也没有看，我不清楚现在陆地是不是用别的模型填充了。
