### ISSUE TITLE
PDF文档有部分内容无法搜索/选中/复制

### ISSUE THREAD

**Issue by zhong-yy** [gmt-china/GMT_docs#806]
## 问题描述
从6.1版本开始，中文手册PDF中，很大一部分的文字内容无法选中或者复制，因此也就无法直接搜索关键字。

## 问题重现
比如，第11章，第178页，第1、2段。

文中大部分汉字无法选中

**Comment by wangliang1989** [comment]
你可不可以把有问题的pdf文件以评论的形式上传到这里，然后再指出页码？

**Comment by zhong-yy** [comment]
比如[中文手册v6.3](https://docs.gmt-china.org/6.3/GMT_docs.pdf)，148页，小节**7.14.2 绝对时间坐标**。章节标题中的文字可以正常复制和搜索，而章节的正文中的内容在ubuntu evince pdf阅读其中无法选中、复制、搜索，在windows的pdf阅读器中，虽然可以选中，但是复制结果是乱码，并且搜索关键词之后，不出现在搜索结果中。

![1](https://user-images.githubusercontent.com/38816011/153141980-d2935ec2-c058-42ac-acf9-d5bf6c57c321.png)

如果是用latex生成的文档，会不会是latex版本的问题？

**Comment by zhong-yy** [comment]
您好，windows测试的pdf阅读器是[Sumatra PDF](https://www.sumatrapdfreader.org/free-pdf-reader) 和 adobe pdf reader.

**Comment by zhong-yy** [comment]
有可能是系统的问题，我刚刚把源码下载下来，在linux下重新生成[GMT_docs_ubuntu20.pdf](https://github.com/gmt-china/GMT_docs/files/8038667/GMT_docs_ubuntu20.pdf)之后，发现可以正常复制了。谢谢！
