### ISSUE TITLE
grdmath 中文文档

### ISSUE THREAD

**Issue by seisman** [gmt-china/GMT_docs#816]
有用户向中文社区投稿了 grdmath 的中文翻译（见附件的 Word 文档），有兴趣的可以帮忙整理为 rst 文档并提交 PR。

请注意：有意愿整理的用户请先回复以认领 issue，以免多人做重复工作。

[grdmath翻译.docx](https://github.com/gmt-china/GMT_docs/files/8141562/grdmath.docx)

**Comment by seisman** [comment]
我用 pandoc 将上面的 word 文档转换成了 rst 文档，大致格式是对的，部分内容还需要做一些调整。

rst 文档见附件: [grdmath.txt](https://github.com/gmt-china/GMT_docs/files/8141583/grdmath.txt)

**Comment by ZMAlt** [comment]
我可以。

> grdmath翻译.docx

这个文档可以下载，但是打不开。从 grdmath.txt 来看，主要贡献在运算符和示例的翻译。但是我个人倾向于不翻译操作符那个表。

**Comment by seisman** [comment]
> 但是我个人倾向于不翻译操作符那个表。

I agree.
