### ISSUE TITLE
中文社区的例子所用的数据应该提供脚本内的下载？

### ISSUE THREAD

**Issue by wangliang1989** [gmt-china/GMT_docs#844]
在脚本内用命令下载数据：
````
wget ...
然后画图
````

**Comment by seisman** [comment]
1. 并非所有系统都安装了 wget
2. 大部分使用了数据的脚本，在脚本之前都有相关数据的下载链接

**Comment by wangliang1989** [comment]
> 1. 并非所有系统都安装了 wget
> 2. 大部分使用了数据的脚本，在脚本之前都有相关数据的下载链接

BAT脚本用wget的替代品，Windows的cmd里肯定有下载文件的命令

**Comment by seisman** [comment]
> BAT脚本用wget的替代品，Windows的cmd里肯定有下载文件的命令

并没有

**Comment by wangliang1989** [comment]
> > BAT脚本用wget的替代品，Windows的cmd里肯定有下载文件的命令
> 
> 并没有

https://www.jianshu.com/p/afb1e7b8acaf

**Comment by seisman** [comment]
> > > BAT脚本用wget的替代品，Windows的cmd里肯定有下载文件的命令
> > 
> > 
> > 并没有
> 
> [jianshu.com/p/afb1e7b8acaf](https://www.jianshu.com/p/afb1e7b8acaf)

没有一个是用户所熟知的，在这种情况下，直接给出数据下载链接让用户自己手动下载是最简单的方式

**Comment by ZMAlt** [comment]
我觉得以后 win 版本的 gmt 也可以少提，或者直接就推荐 wsl，bat 太弱了

**Comment by seisman** [comment]
> 其实，我们的文档在提供脚本时不是一直以来的原则都是不考虑windows用户嘛？

是，又回到了第一点：“并非所有系统都安装了 wget”。
