### ISSUE TITLE
文档内统一使用“角度”，“角分”和“角秒”

### ISSUE THREAD

**Issue by seisman** [gmt-china/GMT_docs#881]
我觉得弧分和弧度里的弧不是一个东西就很奇怪，弧分就是角分，弧度却不是角度。这里实际上应该是角度，而不是弧度。 我建议去掉所有的弧字，不影响理解

_Originally posted by @ZMAlt in https://github.com/gmt-china/GMT_docs/pull/880#discussion_r886575606_

**Comment by core-man** [comment]
默认情况，我们说到度的时候应该默认是角度，而不是弧度吧。所以所有是角度，而不是弧度的地方，似乎可以只用”度“。

弧分/角分、弧秒/角秒也可以只用分和秒，一般在上下文语境中，应该是可以知道这是讨论长度，而非时间等。
