### ISSUE TITLE
Windows 下推荐 WSL?

### ISSUE THREAD

**Issue by seisman** [gmt-china/GMT_docs#911]
在 [Windows 下安装 GMT](https://docs.gmt-china.org/latest/install/windows/) 中，我们目前推荐的方式是 Git for Windows or UnixTools，这里可能存在两个问题：

1. 用户可能会误解 Git for Windows 和 UnixTools 两个都需要安装
2. 也许我们应该直接推荐 WSL？

**Comment by ZMAlt** [comment]
早该推荐了。估计以后 git bash, cygwin 等都会被挤掉。现在的 wsl + win terminal 已经非常好用了

**Comment by ZMAlt** [comment]
或许可以先翻译一下这部分 https://docs.generic-mapping-tools.org/6.4/cookbook/non-unix-platforms.html#gmt-on-non-unix-platforms

**Comment by seisman** [comment]
感觉这部分内容都已经过时了。

**Comment by seisman** [comment]
感觉这部分内容都已经过时了。

**Comment by seisman** [comment]
感觉这部分内容都已经过时了。

**Comment by seisman** [comment]
感觉这部分内容都已经过时了。

**Comment by ZMAlt** [comment]
确实，就像我上面说的，自从 wsl 出来，其他的都基本不怎么用了

**Comment by seisman** [comment]
Windows 下用 GMT 的 exe 安装包安装，然后在 WSL 里调用，是否可行？

**Comment by ZMAlt** [comment]
不行吧，可行的应该是 Mingw 那一套。

**Comment by seisman** [comment]
更多的讨论见 https://github.com/gmt-china/GMT_docs/issues/1203
