### ISSUE TITLE
是否可以删除 CN-block 数据？

### ISSUE THREAD

**Issue by CovMat** [gmt-china/GMT_docs#949]
我认为可以删除 https://docs.gmt-china.org/latest/dataset-CN/CN-block 

现在已经有了更新更完整的 global_tectonics 数据
https://github.com/gmt-china/GMT_docs/pull/948

**Comment by seisman** [comment]
从目前的三张图来看，没法确认 global_tectonics 的数据在中国区域与 CN-block 里的数据是一致的。

**Comment by CovMat** [comment]
![BLOCK](https://user-images.githubusercontent.com/26203721/185514802-7274c8b5-c433-4c09-8f9f-86705e1d19ee.png)
黑色是新数据。感觉新数据更准确一点

**Comment by core-man** [comment]
> 黑色是新数据。感觉新数据更准确一点

我不这么认为。

**Comment by seisman** [comment]
我觉得还是不能删除CN-block。主要原因在于：

1. 黑色数据和 CN-block 的数据明显还是不一样的
2. 黑色数据比 CN-block 多了很多小的块体，这并不一定是用户需要的，有些时候大家只想要显示最带的块体
3. CN-block 数据是张培震的文章里数字化出来的。这篇文章本身引用率就很高，所以还是有很多人会想要用这篇文章里的数据，而不是其他数据
