### ISSUE TITLE
关于grd2xyz的问题

### ISSUE THREAD

**Issue by mayzuishuai** [gmt-china/GMT_docs#986]
从SIO下载的地形数据，扣出来了3度的TOPO.grd，然后对TOPO.grd 进行grdsample操作，范围不变，分辨率选为1m，输出为topo.grd。然后用grd2xyz topo.grd >topo.xyz 。topo.xyz的数据只有180*179=32220行数据，应该数据量是180*180=32400行，请问问题出在哪，望解答！

**Comment by CovMat** [comment]
建议加qq群问

**Comment by mayzuishuai** [comment]
可以给下群号吗，我没有找到欸，谢谢！

**Comment by mayzuishuai** [comment]
> 建议加qq群问

可以给下群号吗，我没有找到欸，谢谢！

**Comment by CovMat** [comment]
https://docs.gmt-china.org/latest/intro/resources/

**Comment by mayzuishuai** [comment]
> https://docs.gmt-china.org/latest/intro/resources/

谢谢！
