### ISSUE TITLE
增加简单示例代码

### ISSUE THREAD

**Issue by SeisPider** [gmt-china/GMT_docs#99]
- 完善部分简单示例代码：[线条](https://docs.gmt-china.org/5.4.5/gallery/lines/) [符号](https://docs.gmt-china.org/5.4.5/gallery/symbols/) [海岸线](https://docs.gmt-china.org/5.4.5/gallery/coast/)

- 新添示例代码种类: 绘制双 Y 轴， 绘制速度分布图等

**Comment by seisman** [comment]
双Y轴可以放在底图那一节内。
